#!/usr/bin/env bash

function echoerr() { printf "%s\n" "$*" >&2; }

[ "$WDC_DO_COMMANDS_DIR" == "" ] && echoerr "Missing WDC_DO_COMMANDS_DIR." && exit

[ "$AZ_TENANT_ID" == "" ] && echoerr "Missing AZ_TENANT_ID" && exit 
[ "$AZ_USERNAME" == "" ] && echoerr "Missing AZ_USERNAME" && exit 
[ "$AZ_DATA" == "" ] \
  && AZ_DATA="${WDC_DO_COMMANDS_DIR}/az/data"

[ ! -d "$AZ_DATA" ] && mkdir -p "$AZ_DATA"

az_subs="${AZ_DATA}/azure_subscriptions"
az_subs_json="${az_subs}.json"
az_subs_csv="${az_subs}.csv"

az login -u "$AZ_USERNAME" --tenant "$AZ_TENANT_ID" | tee "${az_subs_json}"

[ -f "$az_subs_json" ] && cat "$az_subs_json" | jq -r '.[] | "\(.name),\(.id),\(.state)"' | grep Enabled | cut -d',' -f1,2 | sort > "$az_subs_csv"
