#!/usr/bin/env bash

[ "$(which az)" == "" ] && echo "Missing az command" && exit

# shellcheck disable=SC2086
if [ -z ${AZ_SUBSCRIPTION_NAME} ] || [ "$AZ_SUBSCRIPTION_NAME" == "" ]; then
	echo "AZ_SUBSCRIPTION_NAME not defined!"
	exit 1
fi
# shellcheck disable=SC2086
if [ -z ${RESOURCE_GROUP_NAME} ] || [ "$RESOURCE_GROUP_NAME" == "" ]; then
	echo "RESOURCE_GROUP_NAME not defined!"
	exit 1
fi

CLUSTER_NAME="$(echo $RESOURCE_GROUP_NAME|tr '_' '-')-k8s"

az aks get-credentials --subscription "$AZ_SUBSCRIPTION_NAME" --name "$CLUSTER_NAME" --resource-group "${RESOURCE_GROUP_NAME}"
