#!/usr/bin/env bash

function usage()
{
    cmd=$(basename $0)
    echo "Usage: $cmd  [-c] [-d] [-f <folders>]"
    echo "              -c                      : clean before update"
    echo "              -d                      : debug mode"
    echo "              -f                      : folders to consider"
}

# TODO: add options to specife type of files to consider
# -c -> h,c
# -m -> makefiles, kconfig
# -s -> s,S
# -C -> cpp, hpp
# -g -> cfg, const
# -a -> all the rest

folders="."
while getopts hcdf: flag
do
    case $flag in

        c)
            if [ -f "cscope.files" ]
            then
                echo "Cleaning cscope files..."
                rm cscope.*
            fi
            ;;
        d)
            echo debugging on
            ;;
        f)
            folders=$OPTARG
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift past the last flag or argument

check=`which cscope`
if [ -z "$check" ]; then
    echo "Error: cannot find cscope command"
    exit
fi

home=$PWD

echo Home: $home
echo Folders to scan are: $folders

if [ ! -f "cscope.files" ]
then
    echo "Building cscope source file list..."
    for folder in $folders
    do
        cd $folder
        curdir=`pwd`
        echo "Scanning folder: $curdir ..."
        find `pwd` -name "*.h" >> $home/cscope.files
        find `pwd` -name "*.hpp" >> $home/cscope.files
        find `pwd` -name "*.c" >> $home/cscope.files
        find `pwd` -name "*.cc" >> $home/cscope.files
        find `pwd` -name "*.cpp" >> $home/cscope.files
        find `pwd` -name "*.S" >> $home/cscope.files
        find `pwd` -name "*.s" >> $home/cscope.files
        find `pwd` -name "*.const" >> $home/cscope.files
        find `pwd` -name Makefile >> $home/cscope.files
        find `pwd` -name Kconfig >> $home/cscope.files
        find `pwd` -name "*.cfg" >> $home/cscope.files
        cd $home
    done
fi

echo "Building cscope database..."
cscope -bkq
