#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd [-h] [-r]"
    echo "                  -r           : reverse patch"
}

reverse=0
while getopts hr flag
do
    case $flag in
        r)
            reverse=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


orig_files=$(find .| grep "\.orig$")

echo $orig_files

for file in $orig_files;
do
    cur_file=${file%.orig}
    if [ $reverse -eq 0 ]; then
        cmd="diff -rupN $cur_file $file"
    else
        cmd="diff -rupN $file $cur_file"
    fi
    echo "$cmd"
    eval "$cmd"
done
