#!/usr/bin/env bash

function usage() {
	echo "Usage: $cmd [-q] [-d] [-p] [-r] [-b <branch>] [-B [<branch>] [-s] [-n <num>] [-g]"
	echo "             -b <branch>            : show log of the branch"
	echo "             -a <author>            : show log of the author"
	echo "             -r                     : raw"
	echo "             -d                     : detailed"
	echo "             -s                     : show files status"
	echo "             -p                     : show files patches"
	echo "             -n <num>               : show just <num> logs"
	echo "             -g                     : force graph representation in pipes"
	echo "             -q                     : quiet"
}

quiet=0
raw=0
branch="--all"
hbranch="-"
author=""
files=0
num=-1
piping=0
patch=0
detailed=0
if [ ! -t 1 ]; then
    quiet=1
    raw=1
    piping=1
fi
while getopts hqrb:a:sn:gpdB: flag
do
    case $flag in
        d)
            detailed=1
            ;;
        p)
            patch=1
            ;;
        s)
            files=1
            ;;
        r)
            raw=1
            ;;
        g)
            raw=0
            ;;
        q)
            quiet=1
            ;;
        a)
            author="--author=$OPTARG"
            ;;
        B)
            hbranch="$OPTARG"
            [ "$hbranch" == "\." ] && hbranch=""
            ;;
        b)
            branch=$OPTARG
            ;;
        n)
            num=$OPTARG
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

graph="--graph"
details="--abbrev-commit"
opts=""
if [ $num -gt 0 ]; then
	opts="-$num"
fi
if [ $files -eq 1 ]; then
	graph=""
	details="--name-status"
fi
[ $patch -eq 1 ] && opts+=" --patch" && graph=""

# graph branch oriented
#git log --graph --pretty=format:'%Cred%h%Creset %ad %s %C(yellow)%d%Creset %C(bold blue)<%an>%Creset' --date=short
# graph history oriented
#git log --graph --full-history --all --pretty=format:'%Cred%h%Creset %ad %s %C(yellow)%d%Creset %C(bold blue)<%an>%Creset' --date=short
if [ ! "$hbranch" == "-" ]; then
  #git log --graph --abbrev-commit --decorate  --first-parent --oneline --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white) - [%an]%C(reset)%C(bold yellow)%d%C(reset)' --date=relative "$hbranch" 
  git log --graph --abbrev-commit --decorate  --oneline --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white) - [%an]%C(reset)%C(bold yellow)%d%C(reset)' --date=relative "$hbranch" 
  exit
fi

if [ $raw -eq 0 ]; then
	if [ $piping -eq 0 ]; then
      if [ $detailed -eq 0 ]; then
        git log --oneline --graph --decorate --all
      else
        if [ $quiet -eq 0 ]; then
          echo "> git log $opts $author $graph $branch --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white) - [%an]%C(reset)%C(bold yellow)%d%C(reset)' $details --date=relative $@"
        fi
        git log $opts $author $graph $branch --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white) - [%an]%C(reset)%C(bold yellow)%d%C(reset)' $details --date=relative $@
      fi
  else
	    git log $opts $author $graph $branch --format=format:'%h - (%ar) %s - [%an]%d' $details --date=relative $@
	fi
else
    #git log $opts $author $branch $details --date=relative --format=format:'%h - (%ar) %s - [%an] %d'
    #git log $opts $author $branch $details --format=format:'%h - (%aI) %s - [%an] %d'
    if [ $quiet -eq 0 ]; then
    	echo "> git log $opts $author $branch $details --date=unix --format=format:'%h - (%cd) %s - [%an] %d'"
	 fi
    git log $opts $author $branch $details --date=unix --format=format:'%h - (%cd) %s - [%an] %d'
fi
