#!/usr/bin/env bash

cmd="git status -s"

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [<grep-regex>]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -q                          : quiet"
    echo ""
    echo "   ex: $cmd         ---> list changed files"
    echo "   ex: $cmd firm    ---> list just the paths of changed files whose filename contains the \"firm\" string"
    echo "   ex: $cmd .       ---> list just the paths of all changes"
}

# Arguments processing
quiet=0
while getopts hq flag
do
    case $flag in
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -eq 0 ]
then
    cmd="git status -s"
else
    cmd="git status -s  | grep $1 | awk '{ print \$2 }'"
fi

# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
