#!/usr/bin/env bash

# credits to: https://medium.com/@GroundControl/better-git-diffs-with-fzf-89083739a9cb

[ ! -d '.git' ] && echo "Not in the git root folder" && exit

fd() {
  preview="git diff $@ --color=always -- {-1}"
  git diff $@ --name-only | fzf -m --ansi --preview "$preview"
}

fd $@
