#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd <rev> [<path>]"
}

if [ ! $# -gt 0 ]; then
    usage
    exit
fi

rev=$1
shift

if [ $# -gt 0 ]; then
		  #cmd="git show --summary --oneline --date=unix --format=format:'%h - (%cd) %s - [%an] %d' $rev:$@"
		  cmd="git show --summary --oneline --date=unix --format=format:'%h - (%cI) %s - [%an] %d' $rev:$@"
else
		  #cmd="git show --summary --oneline --date=unix --format=format:'%h - (%cd) %s - [%an] %d' $rev"
		  cmd="git show --summary --oneline --date=unix --format=format:'%h - (%cI) %s - [%an] %d' $rev"
fi
echo "> $cmd"
eval $cmd

