#!/usr/bin/env bash

# See https://github.com/smtlaissezfaire/git-shell-scripts.git
 
cmd=$(basename $0)

function output_help {
    echo "Usage: $cmd <sha1>"
}
 
sha1=$1
 
if [[ $sha1 ]]; then
    git diff $sha1..$sha1^ | patch -p1
else
    output_help
fi
