#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-a] [<target_branch>]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -a                          : list merge commits"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
all=0
while getopts hqa flag
do
    case $flag in
	q)
	    quiet=1
	    ;;
	a)
	    all=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -eq 0 ]; then
	target=$(do-git-get-parent-branch)
else
	target="$1"
fi

filter="develop\|master"
options="--no-merges"

if [ $all -eq 1 ]; then
	options=""
fi

git branch|grep -v $filter | tr "*" " "| xargs -I@ sh -c "echo \"git log $target..@\"; git log --oneline $options $target..@ | head -10" | grep --color "^\|git log .*"
