#!/usr/bin/env bash
[ -z $WDC_DO_COMMANDS_DIR ] && echo "Undefined WDC_DO_COMMANDS_DIR." && return
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit
cntfile="$(echo $WDC_DO_COMMANDS_DIR/do_cmd_counts.csv)"
[ ! -f "$cntfile" ] && touch "$cntfile"
idxfile="$(echo $WDC_DO_COMMANDS_DIR/do_cmd_index.csv)"
[ ! -f "$idxfile" ] && touch "$idxfile"
idx="d${1}";shift
[ "$idx" == "d-h" ] && 
  echo "d [-h] [-s [<patt>]] [-d [<patt>]] [-c [<patt>]] [-v] <abbr> [<params>]" && 
  echo "d -h          : help" &&
  echo "d -v          : verbose" &&
  echo "d -s [<patt>] : list commands abbreviations filtered by <patt>" &&
  echo "d -d [<patt>] : list commands filtered by <patt>" &&
  echo "d -c [<patt>] : list usage counter filtered by <patt>" && return
cmd="";verbose=0
[ "$idx" == "d-v" ] && verbose=1 && idx="d${1}" && shift
[ "$idx" == "d-s" ] && do-cmd-index -t "^d[a-z]*${1}.*;" | grep "${1}"  && return
[ "$idx" == "d-d" ] && do-cmd-index -t "do-.*${1}.*" | grep "${1}"  && return
[ "$idx" == "d-c" ] && cat "$cntfile" | while IFS=';' read -r cmd count; do sc=$(do-cmd-index ";$cmd$"|cut -d';' -f1);echo "${sc:----};$cmd;$count"; done |sort -t';' -n -r -k3| column -s ';' -t | grep "${1:-^}" && return
[ "${idx:0:2}" == "d-" ] && echo "Wrong option. Use d -h to get availble options." && return 
cmdname=$(cat "$idxfile"|grep "^${idx};"|cut -d';' -f2|tr -d ' ')
[ "$cmdname" == "" ] && echo "No command found for $idx" && return
[ $(grep -c "$cmdname" "$cntfile") -eq 0 ] && read -p "First use of the command (${cmdname})! Continue? (y/[n]) " ans && [ ! "$ans" == "y" ] && return 
cmd="$cmd $cmdname" && for par in "$@"; do cmd="$cmd \"${par}\""; done
[ -t 0 ] && echo "> $cmd"
[ $(grep -c "$cmdname" "$cntfile" 2>/dev/null) -eq 0 ] && echo "${cmdname};0" >> "$cntfile"
eval "sed -i 's/^\(${cmdname}\);\([0-9]\+\)/echo \"\1;\$((\2+1))\"/ge' $cntfile" && cp "$cntfile" "${cntfile}.bak"
[ $verbose -eq 1 ] && cmd="set -x;$cmd;set +x"
eval "$cmd"
