#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-a] <folder> [<post-fix>]"
    echo "Where:"
    echo "            -a               : all files"
}

quiet=0
all=0
while getopts haq flag
do
    case $flag in
        q)
            quiet=1
            ;;
        a)
            all=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [[ $# < 1 || $# > 2 ]]
then
    usage
    exit
fi


if [ ! -d "$1" ]
then
    echo "Missing folder $1"
    exit
fi

folder_path=`echo ${1%/}`
filename=`basename $folder_path`
curdate="`date '+%y%m%d-%H%M%S'`"

if [ $2 ]; then
	tarfile="$filename-$curdate-$2.tar.bz2"
else
	tarfile="$filename-$curdate.tar.bz2"
fi


if [ $all -eq 0 ]; then
    cmd="tar -cjf ${tarfile}  --exclude=.git --exclude=.svn --exclude=initramfs --exclude=initramfs_dbg --exclude=*.boot ${folder_path}/"
else
    cmd="tar -cjf ${tarfile} ${folder_path}/"
fi
echo "> $cmd"
eval $cmd
