#!/bin/bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd <folder> [<post-fix>]"
}

if [[ $# < 1 || $# > 2 ]]
then
    usage
    exit
fi

if [ $# == 1 ]; then
    if [ "$1" == "-h" ]; then
        usage
        exit
    fi
fi


if [ ! -d "$1" ]
then
    echo "Missing folder $1"
    exit
fi

folder_path=`echo ${1%/}`
filename=`basename $folder_path`
curdate="`date '+%y%m%d-%H%M%S'`"

if [ $2 ]; then
	tarfile="$filename-$curdate-$2.tar.bz2"
else
	tarfile="$filename-$curdate.tar.bz2"
fi


#tar -cjf custom_soc_$curdate.tar.bz2 --exclude=.git --exclude=manta.kernel --exclude=vmlinux --exclude=initramfs --exclude=initramfs_dbg --exclude=*.boot custom_soc/
cmd="tar -cjf ${tarfile}  --exclude=.git --exclude=.svn --exclude=initramfs --exclude=initramfs_dbg --exclude=*.boot ${folder_path}/"
echo "> $cmd"
eval $cmd
