#!/usr/bin/env bash

if [ ! $# == 1 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <tar-archive>"
    exit
fi

if [ ! -f "$1" ]; then
    echo "Error: missing file $1"
    exit
fi


# check extension: tar.bz2, tar.gz

cmd="tar"
ext=".tgz"
opt="zf"
tst="t"
pst=""
check=`echo $1 | grep $ext`
if [ -z "$check" ]; then
    cmd="tar"
    ext=".tar.gz"
    opt="zf"
    tst="t"
    pst=""
    check=`echo $1 | grep $ext`
    if [ -z "$check" ]; then
        ext=".tar.bz2"
        opt="jf"
        check=`echo $1 | grep $ext`
        if [ -z "$check" ]; then
            cmd="unzip"
            ext=".zip"
            opt="qq"
            tst="l"
            pst="| awk '{ print \$NF }'"
            check=`echo $1 | grep $ext`
            if [ -z "$check" ]; then
                echo "Error: unknow extension"
                exit
            fi
        fi
    fi
fi

file=${1%$ext}


# list content of archive
cmd_exe="$cmd -${tst}${opt} $1 $pst | head -20"
eval $cmd_exe

#TODO: check if a folder will be created

echo "..."

read -p "Untar? <y|n>" ans


if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
    # check if destination folder already exists
    folder=`eval $cmd_exe | head -1`
    if [ -d "$folder" ]; then
        echo "Error: $folder already exists"
        exit
    fi

    if [ $cmd=="tar" ]; then
        cmd_exe="$cmd -x${opt} $1"
    else
        if [ $cmd=="unzip" ]; then
            cmd_exe="$cmd ${opt} $1"
        fi
    fi
    echo "> $cmd_exe"
    eval $cmd_exe
    # TODO: cd into the untarred folder
fi

