#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
   echo "Usage: $cmd [-h] [-i] [-f <pattern>]"
   echo "where:"
   echo "       -h                          : print this help"
   echo "       -i                          : info about remotes"
   echo "       -f <pattern>                : filtered info about remotes"
   #echo "       -n                          : dry run"
   #echo "       -v                          : verbose"
   #echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
force=0
exclude=""
dryrun=0
verbose=0
info=0
filter=""
while getopts hif: flag
do
case $flag in
  i)
      info=1
      ;;
  f)
      info=1
      filter=$OPTARG
      ;;
  v)
      verbose=1
      ;;
  q)
      quiet=1
      ;;
  n)
      dryrun=1
      ;;
  h)
      usage
      exit
      ;;
  ?)
      usage
      exit
      ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


if [ "$ANSIBLE_HOSTS" == "" ]; then
    echo "Missing ANSIBLE_HOSTS"
    exit
fi
if [ "$ANSIBLE_USER" == "" ]; then
    echo "Missing ANSIBLE_USER"
    exit
fi

if [ $info -eq 1 ]; then
    if [ "$filter" == "" ]; then
        #cmd="ansible -i $ANSIBLE_HOSTS all -m setup -a \"filter=ansible_distribution*\" --user=$ANSIBLE_USER"
        cmd="ansible -i $ANSIBLE_HOSTS all -m setup --user=$ANSIBLE_USER"
    else
        cmd="ansible -i $ANSIBLE_HOSTS all -m setup -a \"filter=*$filter*\" --user=$ANSIBLE_USER"
    fi
else
    cmd="ansible-playbook -i $ANSIBLE_HOSTS $1 --user=$ANSIBLE_USER"
fi

echo "> $cmd"
eval "$cmd"
