#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
	echo "Usage: $cmd [-h] "
	echo "where:"
	echo "       -h                          : print this help"
	echo "       -q                          : quiet"
	echo "       -n                          : dry run"
}


quiet=0
sorting="sort=stars"
order="order=desc"
dryrun=0
while getopts hqn flag
do
	case $flag in
		n)
			dryrun=1
			;;
		q)
			quiet=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# == 0 ]; then
    echo "Missing name of the artifact to search"
    exit
fi

if [ "$ARTIFACTORY_SERVER" == "" ]; then
    echo "ARTIFACTORY_SERVER not defined"
    exit
fi

if [ "$ARTIFACTORY_REPO" == "" ]; then
    echo "ARTIFACTORY_REPO not defined"
    exit
fi

name="$1"
cmd="curl -sS -H \"\" \"https://$ARTIFACTORY_SERVER/artifactory/api/search/artifact?name=$name&repos=$ARTIFACTORY_REPO\""
if [ $quiet -eq 0 ]; then
	echo "> $cmd"
fi
if [ $dryrun -eq 0 ]; then
    eval "$cmd"
fi

