#!/usr/bin/env bash


cpath=`pwd`
bookmarks=~/.bookmarks
 # check if the bookmark is not already present
n=`cat $bookmarks | grep -E "^$cpath$" | wc -l`

if [ $n == 0 ]; then
    echo "$cpath" >> $bookmarks
fi
file=`cat $bookmarks`;echo  "$file" | sort > $bookmarks
cat $bookmarks
