#!/usr/bin/env bash

if [ "${BACKUP_DIR}" == "" ]
then
  echo "Please, set BACKUP_DIR"
  exit
fi

if [ "${DOCUMENTS_DIR}" == "" ]
then
  echo "Please, set DOCUMENTS_DIR"
  exit
fi


cd "$DOCUMENTS_DIR"

do-list-uniq-text-files | do-pipe-trimmed | do-pipe-no-empty-lines | do-pipe-files-to-backup-archive || { echo 'Failed' ; exit 1; }

backup=$(ls -1t $BACKUP_DIR/ | head -1)

n=$(tar -tzf $BACKUP_DIR/$backup|wc -l)

echo "Backuped $n files"

