#!/usr/bin/env bash 

now=`date +%Y%m%d%H%M%S`

function usage() {
    echo "Usage: do-build-patch [-q] [-x <file-pattern>] <folder> <folder> <output>"
    echo "where:"
    echo "       -x <exclude-patt>  : exclude pattern"
    echo "       -q                 : quiet"
}

exclude=" --exclude=\".git\" --exclude=\".svn\""
quiet=0
while getopts hx:q flag
do
    case $flag in
        q)
            quiet=1
#            echo pars is $pars
            ;;
        x)
            exclude="$exclude --exclude=\"$OPTARG\" "
#            echo pars is $pars
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# -eq 3 ]; then
    usage
    exit
fi

if [ ! -d "$1" ]
then    
    echo "$1 is not a folder"
    exit
fi


if [ ! -d "$2" ]
then
    echo "$2 is not a folder"
    exit
fi

output=$3-$now.patch


if [ "$exclude" == "" ]; then
    cmd="diff -rupN $1 $2 > $output"
else
    cmd="diff $exclude -rupN $1 $2 > $output"
fi

if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd

