#!/usr/bin/env bash


cpath=`pwd`
 # check if the bookmark is not already present
n=`cat ~/.bookmarks | grep -E "^$cpath$" | wc -l`

if [ $n == 0 ]; then
    echo "$cpath" >> ~/.bookmarks
fi
cat ~/.bookmarks
