#!/usr/bin/env bash


cpath=`pwd`
bookmarks=~/.bookmarks

if [ "$PROJECT" == "" ]; then
    list=`cat $bookmarks | grep -v $PROJECTS | xargs -I@ sh -c "if [ -d @ ]; then echo @; fi"| sed "s#$HOME/##"`
else
    list=`cat $bookmarks | grep "$PROJECT_PATH/" | xargs -I@ sh -c "if [ -d @ ]; then echo @; fi"| sed "s#$PROJECT_PATH/##"`
fi

if [ $# -gt 0 ]; then
    if [ $1 == "-h" ]; then
        usage
        exit
    fi
    echo "$list" | grep --color $@
else
    echo "$list"
fi

if [ "$PROJECT" == "" ]; then
    list=`cat $bookmarks | grep -v $PROJECTS | xargs -I@ sh -c "if [ -d @ ]; then echo @; fi"`
else
    list=`cat $bookmarks | grep "$PROJECT_PATH/" | xargs -I@ sh -c "if [ -d @ ]; then echo @; fi"`
fi
