#!/bin/bash


bakfile="backup"
curdate="`date '+%y%m%d-%H%M%S'`"
bakdir=`echo ~/backups`

export MY_VIM_FILES=`eval echo " \
~/git/wdc-vim-generic/README.md \
~/git/wdc-vim-generic/install.sh \
~/git/wdc-vim-generic/vimrc \
"`

export MY_FILES=`eval echo " \
~/bin/* \
~/.bashrc \
~/.bash_aliases \
~/.notebook/* \
$MY_VIM_FILES \
"`

if [ ${#MY_FILES} -eq 0 ]
then
  echo "Please, set MY_FILES"
  exit
fi

files=$MY_FILES
#echo "Backuping $files"


if [ $1 ]; then
	tarfile="$bakfile-$curdate-$1.tar"
else
	tarfile="$bakfile-$curdate.tar"
fi


echo "Creating backups/$tarfile..."
tar -cvf $bakdir/$tarfile --exclude=.git $files
echo "Done."


echo "Creating $tarfile.gz..."
gzip -c $bakdir/$tarfile > $bakdir/$tarfile.gz
echo "Done."


if [ $bakdir/$tarfile.gz ]; then
  echo "Removing $tarfile..."
  rm -f $bakdir/$tarfile
  echo "Done."
  if [ $remote_host ]; then 
    echo "Duplicating backup wdicarlo@$remote_host:walter/backups..."
    #cp $bakdir/$tarfile.gz /mnt/alvs17/backups
    scp $bakdir/$tarfile.gz wdicarlo@$remote_host:walter/backups
    echo "Done."
  fi
fi

