#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd <do-command-name-pattern>"
    echo "Examples:"
    echo "   $cmd   \"list\""
}

if [ $# -ne 1 ]
then
    usage
    exit
fi
folders=`echo ~/bin/`

if [ $# == 1 ]
then
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]
    then
        usage
        exit
    fi
    # TODO: improve filtering considering only the filename but maintaining the path
    list=`find $folders -name "do-*" | grep "$@"`
    num=`ls -1 $list|wc -l`
    if [ "$num" -lt 10 ]
    then
        vim -p `echo $list` < `tty` 
    else
        ls -1 $list
    fi
else
    find $folders -name "do-*"
fi

