#!/bin/bash

if [ ! $# == 2 ]
then
    echo "Usage: "
    exit
fi

if [ ! -d $1 ]
then
    echo "$1 is not a folder"
    exit
fi
if [ ! -d $2 ]
then
    echo "$2 is not a folder"
    exit
fi

cd $1&&find . > ../$1.files&&cd ..
cd $2&&find . > ../$2.files&&cd ..

if [ ! -f $1.files ]
then
    echo "Cannot compare folder files lists"
    exit
fi
if [ ! -f $2.files ]
then
    echo "Cannot compare folder files lists"
    exit
fi

vimdiff $1.files $2.files
