#!/usr/bin/env bash

bin_dir=`echo ~/bin`


function usage() {
    echo "Usage: $cmd [-f] <improved-bin-cmd>"
    echo "where:"
    echo "            -f          : update file (defualt update command)"
}

quiet=0
file=0
while getopts hqf flag
do
	case $flag in
		q)
			quiet=1
			;;
		f)
			file=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cd $bin_dir


if [ ! $# -eq 1 ]; then
    usage
    exit
fi

if [ ! -f $1 ]; then
    echo "Missing file in $bin_dir/$1"
    exit
fi

# TODO: check if the command is already present in the git repository
# check if the command has changes
n=`git diff $1 | wc -l`
if [ $n -eq 0 ]; then
    echo "Command without changes: $1"
    exit
fi

git add $1

if [ $file -eq 0 ]; then
    git commit -m "Improved $1 command. $2"
else
    git commit -m "Update $1 file. $2"
fi
