#!/usr/bin/env bash

bin_dir=`echo ~/bin`

if [ $# -eq 0 ]; then
    echo "Usage: $cmd <bin-cmd>"
    exit
fi

cd $bin_dir

if [ ! -f $1 ]; then
    echo "Missing file in $bin_dir/$1"
    exit
fi

cmd="git diff $1"
echo "> $cmd"
eval "$cmd"
