#!/usr/bin/env bash

bin_dir=`echo ~/bin`

if [ ! $# == 1 ]; then
    echo "Usage: $cmd <improved-bin-cmd>"
    exit
fi

cd $bin_dir

if [ ! -f $1 ]; then
    echo "Missing file in $bin_dir/$1"
    exit
fi

# TODO: check if the command is already present in the git repository
# check if the command has changes
n=`git diff $bin_dir/$1 | wc -l`
if [ $n -eq 0 ]; then
    echo "Command without changes: $1"
    exit
fi

git add $1
git commit -m "Improved $1 command"
