#!/usr/bin/env bash

bin_dir=`echo $WDC_DO_COMMANDS_DIR`

function usage() {
    echo "Usage: $cmd [-f] <new-bin-cmd>"
    echo "where:"
    echo "            -f          : add file (defualt add command)"
}

quiet=0
file=0
while getopts hqf flag
do
	case $flag in
		q)
			quiet=1
			;;
		f)
			file=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cd $bin_dir

if [ ! $# -eq 1 ]; then
    usage
    exit
fi


if [ ! -f $1 ]; then
    echo "Missing file in $bin_dir/$1"
    exit
fi

# TODO: check if the command is not already present in the git repository

git add $1
if [ $file -eq 0 ]; then
	git commit -m "Added $1 command"
else
	git commit -m "Added $1 file"
fi
