#!/usr/bin/env bash

if [ $# == 0 ]; then
    find . -type d | xargs -I@ bash -c "echo -n '@ ' ; find @ -maxdepth 1 -type d -not -path @ | wc -l"
    exit
fi

if [ "$1" == "-h" ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-t <threshold-counting>] [<find-parameters>]"
    exit
fi

num=-1
if [ "$1" == "-t" ]; then
    shift
    num=$1
    shift
fi
if [ "$num" -gt -1 ]; then
    echo "=================================================================="
echo "threshold-counting=$num"
    find $@ -type d | xargs -I@ bash -c "echo -n '@ ' ; find @ -maxdepth 1 -type d -not -path @ | wc -l"
    #echo "STILL UNDER DEVELOPMENT"
else
    find $@ -type d | xargs -I@ bash -c "echo -n '@ ' ; find @ -maxdepth 1 -type d -not -path @ | wc -l"
fi
