#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-v] [-l] [-x] <dot-pattern> [<par>..]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -l                          : list"
    echo "       -x                          : execute command"
    echo "       -v                          : verbose"
}

# Arguments processing
quiet=1
list=0
exe=0
while getopts hve:lx flag
do
    case $flag in
	x)
	    exe=1
	    ;;
	l)
	    list=1
	    ;;
	v)
	    quiet=0
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# == 0 ]; then
    usage
    exit
fi

if [ $exe -eq 0 ]; then
	quiet=0
fi

cd ~/bin

pattern="do"
for patt in $(echo $1| tr '.' '\n')
do
	pattern="$pattern-$patt[a-z]*"
done
shift

if [ $list -eq 1 ]; then
	cmd="ls -1 | grep \"$pattern\""
	if [ "$cmd" == "" ]; then
		echo "Command not found"
		exit
	fi
	cmd="$cmd"
	echo "> $cmd"
	eval $cmd
	exit
fi
cmd=$(ls -1 | grep "$pattern" | head -1)
if [ "$cmd" == "" ]; then
	echo "Command not found"
	exit
fi
cmd="$cmd $@"

# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
if [ $exe -eq 1 ]; then
	eval $cmd
fi

