#!/usr/bin/env bash

if [  $# -lt 2 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-m] <src1>...<srcn> <dst>"
    echo "       Creates <dst> folder if it does not exists"
    exit
fi

move=0
if [ "$1" == "-m" ]; then
    move=1
fi

dest="${@: -1}" # get last parameter

folder=`basename $dest`
n=`echo $folder|grep "\." |wc -l`

if [ $n -gt 0 ]; then
    echo "Folder's name with dot: $folder"
    echo "Are you sure it is the name of the destination folder?"
    exit
fi



#check if dest folder exists
if [ ! -d $dest ]; then
    mkdir -p $dest
fi

curdate="`date '+%y%m%d-%H%M%S'`"
num=$(($# - 1))
count=0
for file in $@; do
    from=$file
    to=$dest/$from
    parent=$(dirname $to)
    if [ ! -d $parent ]; then
        mkdir -p $parent
    fi

    if [ -f $to ]; then
        to="$to-$curdate"
    fi
    if [ $move -eq 1 ]; then
        cmd="mv $from $to"
    else
        cmd="cp $from $to"
    fi
    echo "> $cmd"
    eval "$cmd"
    count=$(($count + 1))
    if [ $count -eq $num ]; then
        break #skip last parameter
    fi
done
last $dest
