#!/bin/bash

prj_root=`echo ~/projects/`
n=0
if [ $# == 1 ]
then
    n=`ls -1 $prj_root | grep $1 | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root | grep $1 | awk '{ print NR, $0 }'
else
    n=`ls -1 $prj_root | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root | awk '{ print NR, $0 }'
fi

num=-1
if [ "$n" == 0 ]
then
    echo "Project/s not found!!!"
    return
fi

if [ "$n" == 1 ]
then
    num=1
else
    read -p "Project Num: " num
fi


if [ $# == 1 ]
then
    prj=`ls -1 $prj_root | grep $1 | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
else
    prj=`ls -1 $prj_root | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
fi

cd "${prj_root}$prj"
