#!/bin/bash

if [ ! $# == 2 ]
then
    cmd=`basename $0`
    echo "Usage: $cmd <find-maxdepth> <find-name-for-folder>"
    exit
fi

#find . -maxdepth "$1" -type d -name "$2" | xargs -I@ sh -c "echo @;find @ | wc -l"
find . -maxdepth "$1" -type d -name "$2" | xargs -I@ sh -c "echo \"\`find @ | wc -l\`\t@\"" | sort  -g
