#!/usr/bin/env bash

bin_dir=`echo ~/bin`

if [ ! $# -gt 0 ]; then
    echo "Usage: $cmd [-f] <improved-bin-cmd>"
    echo "where:"
    echo "            -f          : update file (defualt update command)"
    exit
fi

cd $bin_dir

if [ ! -f $1 ]; then
    echo "Missing file in $bin_dir/$1"
    exit
fi

file=0
if [ "$1" == "-f" ]; then
    file=1
    shift
fi

# TODO: check if the command is already present in the git repository
# check if the command has changes
n=`git diff $bin_dir/$1 | wc -l`
if [ $n -eq 0 ]; then
    echo "Command without changes: $1"
    exit
fi

git add $1

if [ $file -eq 0 ]; then
    git commit -m "Improved $1 command"
else
    git commit -m "Update $1 file"
fi
