#!/usr/bin/env bash

if [ "$1" == "-h" ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-b]"
    echo "            -b         : list just backported packages"
    echo "            -l         : list all packages"
    echo "            -r         : list all repositories"
    exit
fi


if [ "$1" == "-l" ]; then
    dpkg --get-selections
    exit
fi

if [ "$1" == "-r" ]; then
    for APT in `find /etc/apt/ -name \*.list`; do
        grep -Po "(?<=^deb\s).*?(?=#|$)" $APT | while read ENTRY ; do
            HOST=`echo $ENTRY | cut -d/ -f3`
            USER=`echo $ENTRY | cut -d/ -f4`
            PPA=`echo $ENTRY | cut -d/ -f5`
            #echo sudo apt-add-repository ppa:$USER/$PPA
            if [ "ppa.launchpad.net" = "$HOST" ]; then
                echo sudo apt-add-repository ppa:$USER/$PPA
            else
                echo sudo apt-add-repository \'${ENTRY}\'
            fi
        done
    done
    exit
fi

if [ "$1" == "-b" ]; then
    shift
    #dpkg -l  |awk '/^ii/ && $3 ~ /bpo[7]0/ {print $2}'
    dpkg-query -l $@ | grep bpo[7]0
else
    dpkg-query -l $@
fi
