#!/usr/bin/env bash

if [ "$1" == "-h" ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-b]"
    echo "            -b         : list just backported packages"
    echo "            -l         : list all packages"
    exit
fi


if [ "$1" == "-l" ]; then
    dpkg --get-selections
    exit
fi

if [ "$1" == "-b" ]; then
    shift
    #dpkg -l  |awk '/^ii/ && $3 ~ /bpo[7]0/ {print $2}'
    dpkg-query -l $@ | grep bpo[7]0
else
    dpkg-query -l $@
fi
