#!/bin/bash
if [ $# != 1 ]
then
    cmd=`basename $0`
    echo "Usage: $cmd <do-command-command-pattern"
    exit
fi
folders=`echo ~/bin`

if [ $# == 1 ]
then
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]
    then
        cmd=`basename $0`
        echo "Usage: $cmd <do-command-command-pattern"
        echo "Examples:"
        echo "   $cmd   \"list\""
        exit
    fi
    # TODO: improve filtering considering only the filename but maintaining the path
    list=`find $folders -name "do-*" | grep "$@"`
    num=`ls -1 $list|wc -l`
    if [ "$num" == 1 ]
    then
        vim `echo $list` < `tty` 
    else
        ls -1 $list
    fi
else
    find $folders -name "do-*"
fi

