#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] <with-file-ext> <containing> <replace> <with>"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -q                          : quiet"
}

if [ $# == 0 ]; then
    usage
    exit
fi

quiet=0
if [ ! -t 1 ]; then
    quiet=1
fi
while getopts hq flag
do
    case $flag in
        q)
            quiet=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# -eq 4 ]; then
   echo "Wrong parameters"
   usage
fi

do-find-string -p -f "*.$1" $2 | xargs -I@ sed -i'' "s/$3/$4/" @
