#!/usr/bin/env bash



cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-i] [-b] [-p] [-c ][-r <root>] [-n <depth>] [-f <file-pattern>] <string>"
    echo "where:"
    echo "       -i                 : ignore case"
    echo "       -b                 : include binary files"
    echo "       -c                 : just count occurences"
    echo "       -p                 : just print the paths"
    echo "       -r <root>          : start from root folder"
    echo "       -n <depth>         : max depth to search into"
    echo "       -f <file-pattern>  : filename pattern to use"
    echo "       -e <exclude-patt>  : exclude pattern"
    echo "       -a                 : use ack-grep"
    echo "       -q                 : quiet"
    exit
}

if [ $# == 0 ]; then
    usage
    exit
fi

pars="-Hn"
root="."
file="*"
depth=99
postproc=""
exclude=""
quiet=0
binary=0
grep_cmd="\grep"
while getopts abqicpr:n:f:e: flag
do
    case $flag in
        a)
            ack_grep=`which ack-grep`
            if [ ! -z "$ack_grep" ]; then
                grep_cmd="ack-grep"
            fi
            ;;

        b)
            binary=1
            ;;
        q)
            quiet=1
            ;;
        e)
            exclude=$OPTARG
            ;;
        i)
            pars+="i"
            ;;
        p)
            pars="-l"
            ;;
        c)
            # just count occurences, filter out files with not matching the string and revert sort the list
            pars="-Hnc"
            postproc="\grep -v \":0\"| sort -t \":\" -nr -k 2"
            ;;
        f)
            file=$OPTARG
            ;;
        r)
            root=$OPTARG
            ;;
        n)
            depth=$OPTARG
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

string=$1

bin_filter="| xargs file | grep text | cut -d: -f1"
if [ $binary -eq 1 ]; then
    bin_filter=""
fi
if [ "$exclude" == "" ]; then
    cmd="find \"$root\" -maxdepth \"$depth\" \( -type d -name .svn -prune -o -type d -name .git -prune \) -o -type f -name \"$file\" $bin_filter | xargs -I@ $grep_cmd --color \"$pars\" \"$string\" @"
else
    cmd="find \"$root\" -maxdepth \"$depth\" \( -type d -name .svn -prune -o -type d -name .git -prune \) -o -type f -name \"$file\" $bin_filter | xargs -I@ sh -c \"$grep_cmd --color \\\"$pars\\\" \\\"$string\\\" @| \grep -v \\\"$exclude\\\"|\grep --color \\\"$string\\\"\""
fi
if [ ! "$postproc" == "" ]; then
    cmd+="|$postproc"
fi
cmd+=" 2>/dev/null"
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
