#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
   echo "Usage: $cmd [-h] [-q] [-H]"
   echo "where:"
   echo "       -H                          : find MoM in pre-defined folder"
   echo "       -h                          : print this help"
   echo "       -q                          : quiet"
}

DOCUMENTS_DIR=.

# Arguments processing
home=0
opts=""
quiet=0
force=0
exclude=""
dryrun=0
verbose=0
while getopts hqH flag
do
case $flag in
  H)
      home=1
      DOCUMENTS_DIR=$(echo ~/Documents)
      ;;
  f)
      force=1
      ;;
  v)
      verbose=1
      ;;
  q)
      quiet=1
      ;;
  n)
      dryrun=1
      ;;
  e)
      exclude=$OPTARG
      ;;
  h)
      usage
      exit
      ;;
  ?)
      usage
      exit
      ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


if [ ! -d "$DOCUMENTS_DIR" ]; then
    echo "Wrong Document folder: $DOCUMENTS_DIR"
    exit
fi

filenames=$(find $DOCUMENTS_DIR -type f -name "*meeting*.txt" | sort -r)
names=$(echo "$filenames" | sed 's/_[0-9]*\.txt//' | grep -v "\.txt" | uniq)

for name in $names;
do
	file=$(echo "$filenames" | grep "${name}_[0-9]*\.txt" | head -1)
	echo "$file"
done
