#!/bin/bash

if [ ! $# == 3 ] && [ ! $# == 4 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-p] <root> <depth> <string>"
    echo "where:"
    echo "       -p just print the paths"
    exit
fi
pars="-Hni"
if [ "$1" == "-p" ]; then
    shift
    pars="-l"
fi

# postproc='xargs -I@ dirname @ | sort | uniq'
find "$1" -maxdepth "$2" -type f | xargs -I@ grep "$pars" "$3" @
