#!/bin/bash


cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-i] [-r <root>] [-n <depth>] [-s <size-filter>] <file-pattern>"
    echo "where:"
    echo "       -i                 : ignore case"
    echo "       -r <root>          : start from <root> folder"
    echo "       -f <filter>        : filter result with grep <filter>"
    echo "       -n <depth>         : max <depth> to search into"
    echo "       -s <size-filter>   : filter for file size:"
    echo "                             [-+]<val>[cwbkMG]"
    exit
}

if [ $# == 0 ]; then
    usage
    exit
fi

pars="-Hn"
root="."
file="*"
depth=99
while getopts ir:n:f:s: flag
do
    case $flag in

        s)
            size=$OPTARG
            ;;
        i)
            pars+="i"
#            echo pars is $pars
            ;;
        r)
            root=$OPTARG
#            echo root is $root
            ;;
        f)
            filter=$OPTARG
#            echo root is $root
            ;;
        n)
            depth=$OPTARG
#            echo depth is $depth
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ -n "$1" ]; then
    file="$1"
fi

# postproc='xargs -I@ dirname @ | sort | uniq'
#cmd="find \"$root\" -maxdepth \"$depth\" \( -path \"*/.svn\" -prune -o -type f -name \"$file\" \)| xargs -I@ grep \"$pars\" \"$string\" @"
#cmd="find \"$root\" -maxdepth \"$depth\" \( -type d -name .svn -prune -o -type f -name \"$file\" \) | xargs -I@ grep \"$pars\" \"$string\" @"
#cmd="find \"$root\" -maxdepth \"$depth\" -type f -name \"$file\" | grep -v \".svn\|.git\" "
cmd="find \"$root\" -maxdepth \"$depth\" -type f -name \"$file\""
if [ -n "$size" ]; then
    cmd="$cmd -size \"$size\" "
fi
if [ -n "$filter" ]; then
    cmd="$cmd | grep --color $pars $filter "
fi
if [ -n "$size" ]; then
    cmd="$cmd | xargs -I@ ls -lh @  | awk '{ printf \"%-5s  %-60s\n\", \$5, \$9}'"
fi
#find "$root" -maxdepth "$depth" -type f -name "$file"| xargs -I@ grep "$pars" "$string" @
echo "> $cmd"
eval $cmd
