#!/usr/bin/env bash


symbols_patt=$1

folders=$(find . -maxdepth 1 -type d)

for folder in $folders;
do
    cd $folder
    do-find-string $symbols_patt | do-pipe-words $symbols_patt|sed "s#^#$folder #" | sed "s#^./##" | awk '{printf "%-30s  %-30s\n",$1,$2}'
    if [ "$folder" == "." ]; then
        continue
    fi
    cd ..
done
