#!/usr/bin/env bash


if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ]
    then
        app=`basename $0`
        echo "Usage: $app [<find options>]"
        exit
    fi
fi


if [ -z "$SHARED_FOLDER" ]
then
    echo "Variable \$SHARED_FOLDER not defined"
    exit
fi

if [ $# -gt 0 ]
then
    dest=`echo $SHARED_FOLDER/$1`
    shift
else
    dest=$SHARED_FOLDER
fi

if [ ! -d "$dest" ]
then
    echo "Missing shared folder $dest"
    exit
fi

find $dest $@
