#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-s] [-e<filename-pattern>] <containing> <replace> <with>"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -e                          : filename pattern"
    echo "       -s                          : just simulate, no changes"
    echo "       -v                          : verbose"
    echo "       -q                          : quiet"
}

if [ $# == 0 ]; then
    usage
    exit
fi

quiet=0
simulate=0
verbose=0
filenames=""
if [ ! -t 1 ]; then
    quiet=1
fi
while getopts hqsve: flag
do
    case $flag in
        q)
            quiet=1
            ;;
        e)
            filenames="$filenames -f \"$OPTARG\""
            ;;
        v)
            verbose=1
            ;;
        s)
            simulate=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# -eq 3 ]; then
   echo "Wrong parameters"
   usage
fi

sed_opts="-i"
if [ $simulate -eq 1 ]; then
    sed_opts=""
fi

if [ $verbose -eq 0 ]; then
    do-find-string -p $filenames $1 | xargs -I@ sed $sed_opts "s/$2/$3/" @
else
    do-find-string -p $filenames $1 | xargs -I@ sh -c "echo @;sed $sed_opts \"s/$2/$3/\" @"
fi


