#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] "
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -n                          : skip hooks"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
skip=0
while getopts hqn flag
do
    case $flag in
	n)
	    skip=1
	    ;;
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


cmd="git commit"
if [ $skip -eq 1 ]; then
	cmd="$cmd --no-verify"
fi

cmd="$cmd $@"

# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd

