#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd [-l] [-b] <path> <string>"
    echo "             -l                  : list changes"
    echo "             -b                  : blame changes"
    echo ""
}

quiet=0
blame=0
list=0
while getopts hqbl flag
do
	case $flag in
		q)
			quiet=1
			;;
		b)
			blame=1
			;;
		l)
			list=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# == 2 ]; then
	usage
	exit
fi

path="$1"
string="$2"

if [ $list -eq 1 ]; then
	for REV in $(git rev-list --abbrev-commit --all $1); do
		echo "$path"; git show --oneline --no-patch "$REV"
	done
else
	for REV in $(git rev-list --abbrev-commit --all $1); do
		echo "$path"; git show --oneline --no-patch "$REV"
		if [ $blame -eq 0 ]; then
			git diff $REV | grep "^[+-].*$string" | grep --color "$string"
		else
			git blame $REV -- $path|grep ^$REV|grep --color "$string"
		fi
	done
fi
