#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [[-I<paths>]..] <c-file>"
    echo "where:"
    echo "       -d                 : dump tree mode"
    echo "       -I <path>          : include path"
    echo "       -q                 : quiet"
    exit
}

if [ $# == 0 ]; then
    usage
    exit
fi

mode=0  # 0=preprocess, 1=dump-tree
quiet=0
paths=""
while getopts dqI: flag
do
    case $flag in

        d)
            mode=1
            ;;
        q)
            quiet=1
            ;;
        I)
            if [ "$paths" == "" ]; then
                paths=-I$OPTARG
            else
                paths="$paths -I$OPTARG"
            fi
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# == 1 ]; then
    usage
    exit
fi

file=$1
if [ ! -f "$file" ]; then
    echo "Missing file $file"
    exit
fi

if [ "$paths" == "" ]; then
    cmd="gcc "
else
    cmd="gcc $paths "
fi

case $mode in
    0)
        cmd="$cmd -P -E $@"
        ;;
    1)
        cmd="$cmd -fdump-tree-cfg $file 2>&1; cat $file*.cfg && rm $file*.cfg"
        ;;
    ?)
        echo "Unknow mode"
        exit
        ;;
esac

if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
