#!/usr/bin/env bash

# TODO:
# git cherry -v master mybranch # list commits not merged


cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-s <ref_branch>] [-n] [-l]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -n                          : print the name of current branch"
    echo "       -s <ref_branch>             : print branch merge status"
    echo "       -l                          : list branch sorted by date"
    echo "       -q                          : quiet"
}

# if [ $# == 0 ]; then
#     usage
#     exit
# fi

quiet=0
merge=""
while getopts hqs:nl flag
do
    case $flag in
	l)
		cmd="git for-each-ref --sort=-committerdate refs/heads/ --format='%(HEAD) (%(color:green)%(committerdate)%(color:reset)) %(color:red)%(objectname:short)%(color:reset) - %(color:yellow)%(refname:short)%(color:reset) - %(contents:subject) - %(authorname)'"
		# Quieting command output
		if [ $quiet -eq 0 ]; then
		    echo "> $cmd"
		fi
		eval $cmd
		exit
	    ;;
	s)
	    merge=$OPTARG
	    ;;
	n)
	    git rev-parse --abbrev-ref HEAD
	    exit
	    ;;
	q)
	    quiet=1
	    ;;
#	e)
#	    exclude=$OPTARG
#	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


if [ "$merge" == "" ]; then
	cmd="echo \"Branches not merged:\"; git branch -vv --no-merged; echo \"Branches already merged:\"; git branch -vv --merged"
	# Quieting command output
	if [ $quiet -eq 0 ]; then
	    echo "> $cmd"
	fi
	eval $cmd
	exit
fi


git branch | grep -v $merge | xargs -I@ sh -c "echo \"\$(git log --oneline --no-merges $merge..@|wc -l) @\"" | sort -r
