#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-n] [-l] [-f]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -n                          : dry run"
    echo "       -l                          : just list the files to be reset"
    echo "       -f                          : force"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
dryrun=0
list=0
force=0
while getopts hqnlf flag
do
case $flag in
	q)
	    quiet=1
	    ;;
	l)
	    list=1
	    ;;
	n)
	    dryrun=1
	    ;;
	f)
	    force=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $list -eq 0 ]; then
	cmd="git ls-files --others --exclude-standard|xargs -I@ rm @; git reset --hard"
else
	cmd="git ls-files -m; git ls-files --others --exclude-standard"
fi

# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
if [ $dryrun -eq 0 ]; then
	if [ $force -eq 0 ] && [ $list -eq 0 ]; then
		# Request user confirmation
		read -p "Are You Sure? <y|n>" ans
		if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
		  echo "Confirmed!!!"
		else
		  echo "Aborted!!!"
		  exit
		fi
	fi
   eval "$cmd"
fi
