#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] <target_branch>"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -q                          : quiet"
}

if [ $# -eq 0 ]; then
	usage
	exit
fi

filter="develop\|master"
target="$1"

git branch|grep -v $filter | tr "*" " "| xargs -I@ sh -c "echo \"git log $target..@\"; git log --oneline $target..@"
