#!/bin/bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd <repo-url> [<dest-folder>]"
}


#if [  $# -lt 1 ] || [ $# -gt 2 ]; then
if [ ! $# == 2 ]; then
    usage
    exit
fi

repo_url=$1
if [ $# == 1 ]; then
    # TODO: extract folder name from git url
#    repo_folder=$2
    repo_folder=""
else
    repo_folder=$2
fi

git clone $repo_url $repo_folder

echo -e "
[user]
	name = Walter Di Carlo
	email = walter@di-carlo.it
" >> $repo_folder/.git/config
