#!/usr/bin/env   bash

cmd=`basename $0`
execmd="(do-git-log -q | head -5);git status ."

function usage() {
    echo "Usage: $cmd [-u] [-q] <string>"
    echo "where:"
    echo "       -h                 : help"
    echo "       -u                 : equivalent to --untracked-files=no or -uno"
    echo "       -q                 : quiet"
    exit
}

quiet=0
tracked=1
while getopts quh flag
do
    case $flag in

        q)
            quiet=1
            #exclude=$OPTARG
#            echo pars is $pars
            ;;
        u)
            tracked=0
            #exclude=$OPTARG
#            echo pars is $pars
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $tracked -eq 0 ]; then
    #execmd+=" --untracked-files=no"
    execmd+=" -uno"
fi


if [ ! $# == 0 ]
then
    # by default get the status of the local folders
    execmd+=" | grep -e \"$1\|# \w\" "
fi
if [ $quiet -eq 0 ]; then
    echo "> $execmd"
fi
eval $execmd
