#!/usr/bin/env bash


function usage() {
        cmd=`basename $0`
        echo "Usage: $cmd [-u] [<grep-parameters]"
	echo "             -u                    : do not list untraked files"
}

quiet=0
untracked=1
while getopts hqu flag
do
	case $flag in
		q)
			quiet=1
			;;
		u)
			untracked=0
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


opts=""
if [ $untracked -eq 0 ]; then
	opts="-uno"
fi


if [ $# -gt 0 ]
then
    git status -s $opts| awk '{ print $2 }' | grep $@
else
    git status -s $opts| awk '{ print $2 }'
fi

