#!/usr/bin/env   bash

cmd=`basename $0`
execmd="(do-git-log -q | head -5);git status .|head -20"

function usage() {
    echo "Usage: $cmd [-u] [-p] [-q] <string>"
    echo "where:"
    echo "       -h                 : help"
    echo "       -u                 : equivalent to --untracked-files=no or -uno"
    echo "       -p                 : list paths"
    echo "       -q                 : quiet"
    exit
}

quiet=0
tracked=1
paths=0
while getopts quhp flag
do
    case $flag in
        p)
            paths=1
            ;;
        q)
            quiet=1
            #exclude=$OPTARG
#            echo pars is $pars
            ;;
        u)
            tracked=0
            #exclude=$OPTARG
#            echo pars is $pars
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $tracked -eq 0 ]; then
    #execmd+=" --untracked-files=no"
    execmd+=" -uno"
fi

if [ $paths -eq 1 ]; then
	execmd="git status | grep modified | do-pipe-trimmed -a | do-pipe-columns 2"
fi

if [ ! $# == 0 ]
then
    # by default get the status of the local folders
    execmd+=" | grep -e \"$1\|# \w\" "
fi

	
if [ $quiet -eq 0 ]; then
    echo "> $execmd"
fi
eval $execmd
