#!/usr/bin/env bash

# TODO: use git fetch to check if changes are available

n=$(git status --short|wc -l)
branch=$(git rev-parse --abbrev-ref HEAD)

if [ $n -gt 0 ]; then
	echo "> git stash save -u"
	git stash save -u	# stash modified and untracked files
fi

cmd="git pull origin $branch"
echo "> $cmd"
eval "$cmd"

if [ $n -gt 0 ]; then
	echo "> git stash pop"
	git stash pop
fi
