#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
	echo "Usage: $cmd [-h] [-t <topic>] [<grep-expression>]"
	echo "where:"
	echo "       -h                          : print this help"
	echo "       -t <topic>                  : topic to search"
	echo "       -l <language>               : language to search"
	echo "       -q                          : quiet"
}


quiet=0
topics=""
language="language:lua"
sorting="sort=stars"
order="order=desc"
while getopts hqt:l: flag
do
	case $flag in
		q)
			quiet=1
			;;
		l)
			language="language:$OPTARG"
			;;
		t)
			if [ "$topics" == "" ]; then
				topics="topic:$OPTARG"
			else
				topics="$topics+topic:$OPTARG"
			fi
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

grep_expr=""
if [ $# > 0 ]; then
	grep_expr="$1"
fi

terms=""
for term in $@; do
	if [ "$terms" == "" ]; then
		terms="$term"
	else
		terms="$terms%20$term"
	fi
done

#if [ "$topics" == "" ]; then
#	echo "No topics to search for have been specified"
#	usage
#	exit
#fi

#curl -H "Authentication: token TOKEN" -H "Accept: application/vnd.github.mercy-preview+json" https://api.github.com/search/repositories?q=topic:ruby+topic:rails
cmd="curl -sS -H \"Authentication: token TOKEN\" -H \"Accept: application/vnd.github.mercy-preview+json\" https://api.github.com/search/repositories?q=$terms+$language+$topics&$sorting&$order"
# | grep \"\\\"name\\\"\\|clone_url\\|description\" | tr -d \'\\\"\'|sed \'s/^[ \t]*[a-z_]*://\'|sed \'s/,$//\'|sed \'s/\.git$/\n/\'"

if [ $quiet -eq 0 ]; then
	echo "> $cmd"
fi
eval "$cmd"
