#!/usr/bin/env bash


for folder in `find . -maxdepth 1 -type d|xargs -I@ basename @`
do
    cd "$folder" > /dev/null
    if [ -d .git ]; then
        #rev=`git rev-list --all | head -1`
        rev=`git rev-parse HEAD`
        rep=`git remote -v | grep fetch | awk '{ print $2 }'`
        # layout columns correctly
        echo "$folder $rep  $rev" | awk '{ printf "%-20s %-60s %-40s\n", $1, $2, $3}'
    fi
    cd - > /dev/null
done
