#!/usr/bin/env bash

function usage() {
	cmd=$(basename $0)
	echo "Usage: $cmd <parent> <branch>"
}
if [ $# -ne 2 ]; then
	usage
	exit
fi

# TODO: find parent of either the specified branch or the current one

parent=$1
branch=$2

#git log --oneline --decorate --first-parent  $parent..HEAD # current branch
git log --oneline --decorate --first-parent --no-merges $parent..$branch
