#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-I <paths>] <c-file>"
    echo "where:"
    echo "       -I                 : include paths"
    echo "       -q                 : quiet"
    exit
}

if [ $# == 0 ]; then
    usage
    exit
fi

quiet=0
paths=""
while getopts qI: flag
do
    case $flag in

        q)
            quiet=1
#            echo pars is $pars
            ;;
        I)
            if [ "$paths" == "" ]; then
                paths=-I$OPTARG
            else
                paths="$paths -I$OPTARG"
            fi
#            echo pars is $pars
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ "$paths" == "" ]; then
    cmd="gcc -P -E $@"
else
    cmd="gcc $paths  -P -E $@"
fi
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
