#!/usr/bin/env bash

cmd=`basename $0`
function usage() {
    echo "Usage: $cmd [-h] <trace-file> <elf-file>"
}


if [ ! $# -eq 2 ]; then
   usage
   exit
fi

trace="$1"
symbols="$2"

if [ ! -f "$trace" ]; then
   echo "Missing trace file: $trace"
   exit
fi

if [ ! -f "$symbols" ]; then
   echo "Missing symbols file: $symbols"
   exit
fi

gdb_cmds=`echo $trace.gdb`

cat $trace | grep SEH | sed -e '/Callstack/,/Information about/!d' | do-pipe-trimmed -a | do-pipe-columns 3 | grep "^0x[0-9a-f]*" | grep -v "0x00000000"| sed 's/^/list * /' > "$gdb_cmds"


gdb --batch -x "$gdb_cmds" "$symbols"
