#!/usr/bin/env bash

function usage() {
	echo "Usage: $cmd [-q] [-r] [-b <branch>] [-s] [-n <num>] [-g]"
	echo "             -b <branch>            : show log of the branch"
	echo "             -a <author>            : show log of the author"
	echo "             -r                     : raw"
	echo "             -s                     : show files' status"
	echo "             -n <num>               : show just <num> logs"
	echo "             -g                     : force graph representation in pipes"
	echo "             -q                     : quiet"
}

quiet=0
raw=0
branch="--all"
author=""
files=0
num=-1
piping=0
if [ ! -t 1 ]; then
    quiet=1
    raw=1
    piping=1
fi
while getopts hqrb:a:sn:g flag
do
    case $flag in
        s)
            files=1
            ;;
        r)
            raw=1
            ;;
        g)
            raw=0
            ;;
        q)
            quiet=1
            ;;
        a)
            author="--author=$OPTARG"
            ;;
        b)
            branch=$OPTARG
            ;;
        n)
            num=$OPTARG
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

graph="--graph"
details="--abbrev-commit"
opts=""
if [ $num -gt 0 ]; then
	opts="-$num"
fi
if [ $files -eq 1 ]; then
	graph=""
	details="--name-status"
fi

if [ $quiet -eq 0 ]; then
    echo "> git log $opts $author $graph $branch --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white) - [%an]%C(reset)%C(bold yellow)%d%C(reset)' $details --date=relative $@"
fi
if [ $raw -eq 0 ]; then
	if [ $piping -eq 0 ]; then
	    git log $opts $author $graph $branch --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white) - [%an]%C(reset)%C(bold yellow)%d%C(reset)' $details --date=relative $@
    	else
	    git log $opts $author $graph $branch --format=format:'%h - (%ar) %s - [%an]%d' $details --date=relative $@
	fi
else
    git log $opts $author $branch $details --date=relative --format=format:'%h - (%ar) %s - [%an] %d'
fi
