#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [<grep-pattern>]"
    echo "       -h                          : print this help"
    echo "       -q                          : quiet"
}

quiet=0
while getopts hqe: flag
do
    case $flag in
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

log_cmd="git tag -l -n1"

if [ $# -gt 0 ]
then
    log_cmd="$log_cmd | grep $@"
fi

if [ $quiet -eq 0 ]; then
    echo "> $log_cmd"
fi
eval $log_cmd

