#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-e <file_pattern>]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -e <file_pattern>           : exclude files with <file_pattern> name"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
exclude=""
while getopts hqe: flag
do
    case $flag in
	e)
	    exclude=$OPTARG
	    ;;
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cmd="git diff --staged --name-only"
if [ ! "$exclude" == "" ]; then
	cmd="$cmd | grep -v \"$exclude\""
fi


n=$(eval "$cmd" | wc -l)
if [ $n -eq 0 ]; then
	echo "No staged files"
	exit
fi

# Request user confirmation
read -p "Cleaning staged files. Are You Sure? <y|n>" ans
if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
	echo "Confirmed!!!"
else
	echo "Aborted!!!"
	exit
fi

eval $cmd | while read filepath;
do
	echo "Processing $filepath..."
	do-git-diff-with-linenumbers -s "$filepath"| grep "^[0-9]* +[[:space:]]\+$"|do-pipe-columns 1|xargs -I@ sed -i "@s/^[ \t]\+$//" "$filepath"
	#do-git-diff-with-linenumbers -s "$filepath"| grep "^[0-9]* +\(.*[a-zA-Z0-9;{}>(),.*]\)[[:space:]]\+$"|do-pipe-columns 1|xargs -I@ sed -i "@s/[ \t]\+$//" "$filepath"
	do-git-diff-with-linenumbers -s "$filepath"| grep "^[0-9]* +\(.*[[:graph:]]\)[[:space:]]\+$"|do-pipe-columns 1|xargs -I@ sed -i "@s/[ \t]\+$//" "$filepath"
	done
