#!/usr/bin/env bash

function usage() {
	cmd=$(basename $0)
	echo "Usage: $cmd [-h] [<branch>]"
}

if [ $# -gt 1 ]; then
	if [ "$1" == "-h" ]; then	
		usage
		exit
	fi
fi

branch="$1"
if [ "$branch" == "" ]; then
	branch="HEAD"
fi

git merge-base $branch HEAD
