#!/bin/bash

if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ]
    then
        cmd=`basename $0`
        echo "Usage: $cmd [<grep-parameters>]"
        exit
    fi
    git diff --name-only HEAD~1..HEAD | grep $@
else
    git diff --name-only HEAD~1..HEAD
fi
