#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] "
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
while getopts hq flag
do
    case $flag in
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cmd="git ls-files --others --exclude-standard|xargs -I@ rm @; git reset --hard"

# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
