#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-s] [-a] [-u] [<file>..<file>|file_pattern>]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -s                          : diff of staged changes"
    echo "       -a                          : show all diffs"
    echo "       -c                          : list conflicted files"
    echo "       -u                          : include untracked files"
    echo "       -q                          : quiet"
}


piping=1
quiet=1
staged=0
all=0
conflicts=0
untracked=0
if [ -t 1 ]; then # check if piping to output stream
	piping=0
	quiet=0
fi
while getopts hqsacu flag
do
    case $flag in
	u)
	    untracked=1
	    ;;
	c)
	    conflicts=1
	    ;;
	a)
	    all=1
	    ;;
	q)
	    quiet=1
	    ;;
	s)
	    staged=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

opts="-w"
if [ $all -eq 1 ]; then
	opts=""
fi
if [ $piping -eq 0 ]; then
	opts="$opts --color=always"
fi
if [ $staged -eq 1 ]; then
	opts="$opts --staged"
fi
files="$@"
if [ $# -eq 1 ]; then
	rev=$(git rev-list --all| grep $1 | wc -l)
	if [ $rev -eq 1 ]; then
		rev=$(git rev-list --all| grep $1)
		files="$rev~..$rev"
	elif [ ! -f "$1" ]; then
		files=$(git diff --name-only|grep $1)
	fi
fi

if [ $conflicts -eq 1 ]; then
	cmd="git diff --name-only --diff-filter=U"
else
	#cmd="git diff -w $opts $files | sed \"s/^+[[:space:]]*$/+/g\" | sed \"s/^+\\(.*[;}>]\\)[[:space:]]*$/+\\1/\""
	cmd="git diff $opts $files | do-pipe-diff-without-useless-whitespaces"
fi
if [ $untracked -eq 1 ]; then
		others=$(git ls-files --other --exclude-standard)
		nothers=$(echo "$others"|tr ' ' '\n'|wc -l)
		if [ $nothers -gt 0 ]; then
			for file in $others
			do
				cmd="$cmd; git diff -w --no-index /dev/null $file"
			done
		fi
fi
if [ $quiet -eq 0 ]; then
	echo "> $cmd"
fi
eval $cmd
