#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q]"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -s                          : diff of staged changes"
    echo "       -q                          : quiet"
}


piping=1
quiet=1
staged=0
while getopts hqs flag
do
    case $flag in
	q)
	    quiet=1
	    ;;
	s)
	    staged=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ -t 1 ]; then # check if piping to output stream
	piping=0
	quiet=0
fi
opts=""
if [ $piping -eq 0 ]; then
	opts="--color=always"
fi
if [ $staged -eq 1 ]; then
	opts="$opts --staged"
fi

files="$@"
if [ $# -eq 1 ]; then
	if [ ! -f "$1" ]; then
		files=$(git diff --name-only|grep $1)
	fi
fi

cmd="git diff -w $opts $files"
if [ $quiet -eq 0 ]; then
	echo "> $cmd"
fi
exec $cmd
