#!/bin/bash

log_cmd="do-git-log | grep \"(.*).*—.*(.*)\""
if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ]
    then
        cmd=`basename $0`
        echo "Usage: $cmd [-raw] [<grep-pattern>]"
        echo "       -raw    raw format"
        exit
    fi
    if [ "$1" == "-raw" ]
    then
        log_cmd="git tag -l"
        shift
    fi
fi


if [ $# -gt 0 ]
then
    log_cmd="$log_cmd | grep $@"
fi
echo $log_cmd
eval $log_cmd
