#!/usr/bin/env bash

msg=""


# Usage help function
cmd=`basename $0`

function usage() {
	echo "Usage: $cmd [-h] [-q] [-n] [-f] [-u] [-A|-U] [-m \"<message>\"] <files...>"
	echo "where:"
	echo "       -A                          : add specified file/s using the Add message"
	echo "       -U                          : update specified file/s using the Update message"
	echo "       -u                          : add all files apart the untracked ones"
	echo "       -m \"<message>\"            : commit message"
	echo "       -f                          : force"
	echo "       -h                          : print this help"
	echo "       -n                          : dry run"
	echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
dryrun=0
force=0
all=0
add=0
update=0
while getopts hqnm:fuAU flag
do
	case $flag in
		m)
			msg="$OPTARG"
			;;
		A)
			add=1
			;;
		U)
			update=1
			;;
		u)
			all=1
			;;
		f)
			force=1
			;;
		v)
			verbose=1
			;;
		q)
			quiet=1
			;;
		n)
			dryrun=1
			;;
		e)
			exclude=$OPTARG
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


if [ $# -eq 0 ] && [ $all -eq 0 ]; then
	echo "Missing files to commit"
	exit 1
fi

opts=""
files="$@"

if [ $all -eq 1 ]; then
	opts="-u"
	update=1
	add=0
	files="$(git status -s | grep -v "^?" | cut -d ' ' -f 3 | tr '\n' ' ')"
fi
n=$(echo "$files" | wc -w)
if [ $n -gt 3 ]; then
	msgfiles="$(echo "$files" | cut -d ' ' -f 1-3) ..."
else
	msgfiles="$(echo "$files" | cut -d ' ' -f 1-3)"
fi
if [ $add -eq 1 ]; then
	msg="Added $msgfiles"
fi
if [ $update -eq 1 ]; then
	msg="Updated $msgfiles"
fi

if [ "$msg" == "" ]; then
	echo "Missing commit message"
	exit 1
fi
if [ $all -eq 1 ]; then
	cmd="git add $opts; git commit -m \"$msg\""
else
	cmd="git add $opts $files; git commit -m \"$msg\""
fi

# Quieting command output
if [ $quiet -eq 0 ]; then
	echo "> $cmd"
fi
# Request user confirmation
if [ $force -eq 0 ]; then
	read -p "Are You Sure? <y|n>" ans
	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
		echo "Confirmed!!!"
	else
		echo "Aborted!!!"
		exit
	fi
fi
if [ $dryrun -eq 0 ]; then
	eval "$cmd"
fi
