#!/usr/bin/env bash


# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-c] [-n] <branch_name_pattern>"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -c                          : commit"
    echo "       -n                          : no run"
    echo "       -q                          : quiet"
}

quiet=0
commit=0
run=1
while getopts hqcn flag
do
    case $flag in
	n)
	    run=0
	    ;;
	q)
	    quiet=1
	    ;;
	c)
	    commit=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# == 1 ]
then
    usage
    exit
fi

nbranches=$(git branch | grep -v master | grep -v "^\*" | grep $1 | wc -l)
branch=$(git branch | grep -v master | grep -v "^\*" | grep $1)
if [ $nbranches -ne 1 ]; then
	echo "Please, specify one branch"
	if [ $nbranches -eq 0 ]; then
		echo "$(git branch | grep -v master | grep -v "^\*" )"
	else
		echo "Filtered branches:"
		echo "$branch"
	fi
	exit
fi

options="--strategy recursive -X ignore-all-space"

if [ $commit -eq 0 ]; then
	cmd="git merge $options --no-commit --no-ff $branch"
else
	cmd="git merge $options $branch"
fi
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
if [ $run -eq 1 ]; then
	eval $cmd
fi
