#!/usr/bin/env bash

function usage() {
  cmd=`basename $0`
  echo "Usage: $cmd [-h] [-m\"commit-message\"] <category>"
  echo "       where <category> may be:"
  echo "          git"
  echo "          linux"
  echo "          debian"
  echo "          ..."
}

message=""
while getopts hm: flag
do
	case $flag in
		m)
			message="$OPTARG"
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# == 1 ]
then
  usage
  exit
fi

howto="howto_$1.otl"
howtofile="$WDC_DO_COMMANDS_DIR/$howto"

if [ ! -f "$howtofile" ]; then
    echo "Missing howto file: $howto"
    exit
fi

do-cmd-update -f "$howtofile"
