#!/bin/bash


if [ $# == 0 ]
then
    cmd=`basename $0`
   echo "Usage: $cmd <category> [<keyword>]"
   echo "       where <category> may be:"
   echo "          git"
   echo "          linux"
   echo "          debian"
   echo "          ..."
   echo "             <keyword>       term to search"
   exit
fi

howto=`echo ~/bin/howto_$1.otl`
shift
if [ ! -f $howto ]; then
    echo "Missing howto file for: $1"
    echo "Availanble howto:"
    do-howto-list
    exit
fi

if [ $# -gt 0 ]; then
    cat $howto | grep -A 1 -in $@
else
    cat $howto 
fi
