#!/usr/bin/env bash

cmd=`basename $0`

function quote () { 
    local quoted=${1// /%20};
    quoted=${quoted//=/%3D};
    quoted=${quoted//,/%2C};
    printf "%s" "$quoted"
}
function usage() {
	echo "Usage: $cmd [-h] [-p <num_pages>] [-n] [-i <num_items_per_pages>] [-s <sec_to_sleep>] [-j <jira_server>] <project_id>>"
	echo "where:"
	echo "       -j <jira_server>            : jira server domain name"
	echo "       -s <sec_to_sleep>           : seconds to sleep after each request"
	echo "       -i <num_items_per_pages>    : number of items per page to retrieve"
	echo "       -p <num_pages>              : number of pages to retrieve"
	echo "       -h                          : print this help"
	echo "       -n                          : dry run"
}


dryrun=0
pages=1
items=20
seconds=0
while getopts hnp:i:s:j: flag
do
	case $flag in
		j)
			JIRA_SERVER=$OPTARG
			;;
		s)
			seconds=$OPTARG
			;;
		i)
			items=$OPTARG
			;;
		p)
			pages=$OPTARG
			;;
		n)
			dryrun=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -eq 0 ]; then
    echo "Missing project key"
    exit 1
fi

if [ "$JIRA_SERVER" == "" ]; then
    echo "JIRA_SERVER not defined"
    exit -1
fi

if [ "$DEVOPS_USER" == "" ]; then
    echo "DEVOPS_USER not defined"
    exit -1
fi

if [ "$DEVOPS_PASSWORD" == "" ]; then
    echo "DEVOPS_PASSWORD not defined"
    exit -1
fi

url_api="https://$JIRA_SERVER/rest/api/2/search"
jql="project = $1 ORDER BY priority DESC, updated DESC" # search all issues whatever are their status
jql_url=$(quote "$jql")

if [ $pages -eq -1 ]; then
    cmd="curl -sS -u '$DEVOPS_USER:$DEVOPS_PASSWORD' -H \"Content-Type: application/json\" \"$url_api?startAt=$startAt&maxResults=1&jql=$jql_url\""
    total=$(eval "$cmd" | jq '.total')
    pages=$(( ($total / $items) + 1 ))
fi


opts="-sS"

for counter in $(seq 1 $pages);
do
    startAt=$(( ($counter - 1) * $items))

    cmd="curl -sS -XH -u $DEVOPS_USER:$DEVOPS_PASSWORD -X GET -H \"Content-Type: application/json\" \"$url_api?startAt=$startAt&maxResults=$items&jql=$jql_url\""
    if [ $dryrun -eq 0 ]; then
           eval "$cmd | jq '.issues|.[]'"
    fi
    if [ $counter -lt $pages ] && [ $seconds -gt 0 ]; then
        sleep $seconds
    fi
done | jq -s '.'
