#!/bin/bash

cmd="do-super"


if [ ! `which lsof` ]; then
    echo "Missing lsof command"
    cmd="$cmd sh -c \"netstat -lptu&& netstat -tulpn && ss\""
else
    cmd="$cmd sh -c \"lsof -i&& netstat -lptu&& netstat -tulpn && ss\""
fi
echo "> $cmd"
eval $cmd
