#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-g] <libs-and-or-object-files>"
    echo "                 -g          evaluate all symbols all together"
}

global=0
if [ $# -gt 0 ]; then
    if [ "$1" == "-g" ]; then
        global=1
        shift
    fi
fi


if [ $# == 0 ]; then
    usage
    exit
fi
if [ $global == 0 ]; then
    for file in $@
    do
        iself=`file $file|grep -i "elf"|wc -l`
        if [ "$iself" -gt 0 ]; then
            echo "$file"
            nm $file | grep " T " | do-pipe-columns 3 | sort | uniq --count | grep -v " 1 "
        fi
    done
else
    nm $@ | grep " T " | do-pipe-columns 3 | sort | uniq --count | grep -v " 1 "
fi
