#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-v] [-l] [-c] [-g] [<lua-parameters>]"
    echo "where:"
    echo "       -h                 : help"
    echo "       -v                 : verbose"
    echo "       -l                 : trace lines"
    echo "       -c                 : trace calls"
    echo "       -g                 : trace globals"
    echo "       -p <pkg-path>      : package path to add"
    exit
}

function update_path() {
    if [ $# == 0 ]; then
        return
    fi
    if [ -z "$LUA_PATH" ]; then
        LUA_PATH="$1/?.lua;$1/init.lua"
    else
        LUA_PATH="$1/?.lua;$1/init.lua;$LUA_PATH"
    fi
    echo "Updated LUA_PATH: $LUA_PATH"
    #if [ -z "$LUA_CPATH" ]; then
    #    LUA_CPATH="$1/?.so"
    #else
    #    LUA_CPATH="$1/?.so;$LUA_PATH"
    #fi
    #echo "Updated LUA_CPATH: $LUA_CPATH"
}

if [ -z $LUA_HOME ]; then
    #echo "Please, define LUA_HOME enviroment variable"
    #LUA_HOME=`readlink -f ~/.luarocks/`
    #echo "Default: $LUA_HOME"
    #exit
    LUA_HOME=`echo ~/.luarocks`
fi

if [ ! -d $LUA_HOME ]; then
    echo "Missing folder $LUA_HOME"
    exit
fi

opts=
verbose=0

export LUA_PATH=""

while getopts hvlcgp: flag
do
    case $flag in

        v)
            verbose=1
            ;;
        l)
            opts+=" -ltrace-lines"
            ;;
        c)
            opts+=" -ltrace-calls"
            ;;
        g)
            opts+=" -ltrace-globals"
            ;;
        p)
            pkg_path=$OPTARG
            if [ -d "$pkg_path" ]; then
                echo "Added path: $pkg_path"
                update_path $pkg_path
            fi
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ -z "$LUA_PATH" ]; then
    LUA_PATH=`echo "?.lua;?/init.lua;$LUA_HOME/share/lua/5.1/?.lua;$LUA_HOME/share/lua/5.1/?/init.lua"`
else
    LUA_PATH=`echo "?.lua;?/init.lua;$LUA_PATH;$LUA_HOME/share/lua/5.1/?.lua;$LUA_HOME/share/lua/5.1/?/init.lua"`
fi
export LUA_CPATH=`echo "$LUA_HOME/lib/lua/5.1/?.so;./?.so;?/?.so;$LUA_HOME/lib/lua/5.1/?.so;$LUA_HOME/lib/lua/5.1/loadall.so"`


#export LUA_INIT="package.path = '?;'..package.path"
export LUA_INIT=`echo "package.path = '${LUA_PATH};'..package.path"`


if [ "$verbose" == 1 ]; then
    echo "PATH      = $PATH"
    echo "LUA_PATH  = $LUA_PATH"
    echo "LUA_CPATH = $LUA_CPATH"
    echo "LUA_INIT  = $LUA_INIT"
    echo "options   = $opts"
    echo
fi

lua $opts "$@"
