#!/bin/bash

cmd=""
if [  `which sudo` ]; then
    cmd="sudo"
elif [ `which su-to-root` ]; then
    cmd="su-to-root"
else
    echo "Missing super hero command"
    exit
fi

cmd="$cmd sh -c \"lsof -i&& netstat -lptu&& netstat -tulpn\""
echo "> $cmd"
eval $cmd
