#!/usr/bin/env bash

if [ ! $# == 1 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <required-lib>"
    exit
fi

lua -e "\
    d = require\"$1\"; \
    for k,v in pairs(d) do \
        print (k,v) \
    end"
