#!/bin/bash

cmd=""
if [ -f `which sudo` ]; then
    cmd="sudo"
elif [ -f `which su-to-root` ]; then
    cmd="su-to-root"
else
    echo "Missing super hero command"
    exit
fi

cmd="$cmd sh -c \"lsof -i&& netstat -lptu&& netstat -tulpn\""
echo "> $cmd"
eval $cmd
