#!/bin/bash

if [ ! $# == 1 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <folder>"
    exit
fi

if [ ! -d "$1" ]; then
    echo "Not a folder: $1"
    exit
fi

app_to_check=`which mirage`
if [ ! "$app_to_check" ]; then
    echo "Application mirage is missing, please install it"
    exit
fi

mirage "$1"&
