#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    # by default without any argument print the list of targets
    make -pn | grep "^[a-zA-Z_-]*:" | sed "s/^\([a-zA-Z_-]*\).*/\1/" | sort
    exit
fi

if [ $# -gt 0 ]; then
    if [ "$1" == "-c" ]; then
        targets="clean"
        shift
    fi
fi

# print all executed shell commands
cmd="make SHELL=\"bash -x\" $targets $@"
echo "> $cmd"
eval $cmd
