#!/usr/bin/env bash


if [ "${MONGODB_CONTAINER_NAME}" == "" ]
then
  echo "Please, set MONGODB_CONTAINER_NAME"
  exit 1
fi

if [ "${MONGODB_DB_NAME}" == "" ]
then
  echo "Please, set MONGODB_DB_NAME"
  exit 1
fi

if [ $# -ne 2 ]; then
    echo "do-mongo <collection> <command>"
    echo "MONGODB_CONTAINER_NAME=$MONGODB_CONTAINER_NAME"
    echo "MONGODB_DB_NAME=$MONGODB_DB_NAME"
    exit 0
fi
quote () { 
    local quoted=${1//\"/\\\"};
    quoted=${quoted//\$/\\\$};
    printf "%s" "$quoted"
}

mongo_collection="$1"
mongo_cmd=$(quote "$2")

#cmd="docker run -it --link $MONGODB_CONTAINER_NAME:mongo --rm mongo mongo $MONGODB_DB_NAME --host mongo --eval \"db.${mongo_collection}.${mongo_cmd}.toArray()\""
cmd="docker run -it --link $MONGODB_CONTAINER_NAME:mongo --rm mongo mongo $MONGODB_DB_NAME --host mongo --eval \"db.${mongo_collection}.${mongo_cmd}\""

#echo "> $cmd"
eval "$cmd"
