#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-c] [-u] [-n] <task_pattern>"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -c                          : commit changes"
    echo "       -u                          : add untracked files"
    echo "       -n                          : dry run"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
commit=0
untracked=0
dryrun=0
while getopts hqcun flag
do
    case $flag in
	n)
	    dryrun=1
	    ;;
	u)
	    untracked=1
	    ;;
	c)
	    commit=1
	    ;;
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# == 0 ]; then
    usage
    exit
fi
n=$(do-mylyn-tasks "$1"|wc -l)
if [ $n -ne 1 ]; then
	echo "Number of selected tasks: $n"
	do-mylyn-tasks | grep --color "^\|$1"
	exit
fi

taskname=$(do-mylyn-tasks -w "$1")
commit_comment=$(do-mylyn-tasks "$1")

cmd="git checkout -b $taskname"
if [ $commit -eq 1 ]; then
	if [ $untracked -eq 0 ]; then
			  cmd="$cmd; git add -u; git commit -m \"$commit_comment\""
	else
			  cmd="$cmd; git add .; git commit -m \"$commit_comment\""
	fi
fi
# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
if [ $dryrun -eq 0 ]; then
		  eval "$cmd"
fi

