#!/bin/bash

DOCS_FOLDER=docs
FILENAME=notes.otl

isglobal=0
if [ $# == 1 ]; then
    if [ "$1" == "-g" ]; then
        isglobal=1
    fi
fi


if [ -z "$PROJECT" ] || [ "$isglobal" == "1" ]
then
    dest=`echo ~/$DOCS_FOLDER`
else
    dest=`echo ~/projects/$PROJECT/$DOCS_FOLDER`
fi


if [ ! -d "$dest" ]
then
    mkdir -p $dest
fi

if [ -f "$dest/../$FILENAME" ]; then
    # TODO: create symbolic link
    cat "$dest/../$FILENAME" >> "$dest/$FILENAME"
    mv "$dest/../$FILENAME" "$dest/../${FILENAME}.bak"
    ln -s "$dest/$FILENAME" "$dest/../$FILENAME"
fi

vi $dest/$FILENAME
