#!/usr/bin/env bash

#pipe input:             path/filename linenumber

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

while getopts ha flag
do
    case $flag in
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cat | while read filename linenumber;
do
    #cat "$filename" | do-pipe-lines-numbers | grep "^$linenumber " 
    cat "$filename" | do-pipe-lines-numbers | grep "^$linenumber " | sed "s%^\([0-9]*\) \(.*\)$%${filename}:\1: \2%" 
done
