#!/bin/bash


if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

if [ $# == 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-n] <note-title>"
    echo "             -n         : just print"
    exit
fi

noop=0
if [ "$1" == "-n" ]; then
    shift
    noop=1?
fi

if [ -z "$PROJECT" ]
then
    dest=`echo ~/docs`
else
    dest=`echo $PROJECTS/$PROJECT/docs`
fi


if [ ! -d "$dest" ]
then
    echo "Missing folder $dest"
    exit
fi

cmd=`basename $0`
curdate=`date '+%y_%m_%d_%H_%M'`

if [ $noop -eq 0 ]; then
echo "Note: $@" >> $dest/notes.otl
echo -e "\tDate: $curdate" >> $dest/notes.otl
echo -e "\tReference: $cmd" >> $dest/notes.otl
cat -E| xargs -I@ echo -e "\t; @"|sed 's/$$//' >>  $dest/notes.otl
else
echo "Note: $@"
echo -e "\tDate: $curdate"
echo -e "\tReference: $cmd"
cat -E| xargs -I@ echo -e "\t; @"|sed 's/$$//'
fi
