#!/usr/bin/env bash


function usage() {
    echo "Usage: <list-of-words> | do-pipe-text-without-in <file>"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "$cmd must be used in a pipe"
    usage
    exit
fi


if [ $# -lt 1 ]; then
    usage
    exit
fi

while getopts h flag
do
    case $flag in
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


file=$1
shift



text=$(cat)
#echo $text
for word in $(cat $file); do
    text=$(echo "$text"|\grep -v $word)
done

echo "$text"
