#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
   echo "Usage: $cmd [-h]"
   echo "where:"
   echo "       -h                          : print this help"
   echo "       -s <separator_char>         : use <separator_char> char to indentify columns"
}

# Arguments processing
separator=";"
while getopts hs: flag
do
case $flag in
  s)
      separator="$OPTARG"
      ;;
  h)
      usage
      exit
      ;;
  ?)
      usage
      exit
      ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument



cmd="cat | column -t -s'${separator}'"
eval "$cmd"
