#!/bin/bash
verbose=0



if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    echo "       Example:   ls | $cmd do-list-duplicated-symbols"
    exit
fi

if [ $# == 0 ]; then
    cmd=`basename $0`
    echo "Usage: <pipe> | $cmd [-v] <cmd>"
    echo "      where:"
    echo "             -v               verbose"
    exit
fi

if [ "$1" == "-v" ]; then
    verbose=1
    shift
    if [ $# == 0 ]; then
        echo "Missing command to execute"
        exit
    fi
fi

if [ $verbose -eq 1 ]; then
xargs -I@ sh -c "echo @; $1 @"
else
xargs -I@ sh -c "$1 @"
fi
