#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd <root_ref> <patch_name_without_spaces>"
}

if [ -t 0 ]; then
    usage
    echo ""
    echo "ATTENTION: $cmd must be used in a pipe"
    exit
fi

if [ -z $PATCHES_DIR ]; then
    echo "PATCHES_DIR not defined"
    exit
fi

curdate="`date '+%y%m%d-%H%M%S'`"
file="$PATCHES_DIR/$1-$curdate-$2.diff"
verbose=0
while getopts hv flag
do
    case $flag in
        v)
            verbose=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -ne 2 ]; then
    usage
    exit
fi

if [ $verbose -eq 0 ]; then
    cat > $file
else
    cat | tee $file
fi
num_patched=$(cat $file|grep "^Index"|wc -l)
echo "Created patch: $file"
echo "Patched files: $num_patched"
cat $file|grep "^Index"|sed "s/^Index: //"
