#!/usr/bin/env bash

function usage()
{
    cmd=$(basename $0)
    echo "Usage: <pipe> | $cmd [-v]"
    echo "                      -v            : verbose"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

verbose=0
while getopts hv flag
do
    case $flag in
        v)
            verbose=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


if [ $verbose -eq 1 ]; then
    cat | grep "\[CP\]\|\[GEN\]\|\[AR\]\|\[CC\]\|\[LD\]\|^==="
else
    cat | grep "\[AR\]\|\[CC\]\|\[LD\]"
fi
