#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-hq] <line1-word> <line2-word>"
}


if [ $# == 0 ]; then
    usage
    exit
fi

if [ ! -t 1 ]; then
    echo "Use in pipes"
    usage
    exit
fi
while getopts h flag
do
    case $flag in
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# -eq 2 ]; then
    usage
    exit
fi

cmd="cat | grep -Pzo \"^.*$1.*\\n.*$2.*$\" | grep --color \"$1\\\|$2\""
eval "$cmd"
