#!/usr/bin/env bash


if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

# trim 
#cat | sed "s/^[[:space:]]*\(.*\)[[:space:]]*$/\1/g"
cat | sed "s/^[[:space:]]*//;s/[[:space:]]*$//"
