#!/usr/bin/env bash

# Check it is used correctly	
if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

sed "s/^+[[:space:]]*$/+/g" | sed "s/^+\(.*[a-zA-Z0-9;{}>(),.*]\)[[:space:]]*$/+\1/"
