#!/usr/bin/env bash


if [ $# == 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <file> [<file>...]"
    exit
fi

for file in $@
do
    # print absolute path of the file
    echo `readlink -f $file`
done
