#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

max_files=15
tmp_file=/tmp/vim_paths.txt

#if [ $# -gt 0 ]; then
#    if [ "$1" == "-f" ]; then
#        max_files=50
#        shift
#    fi
#fi
opts="-p"
while getopts Oofh flag
do
    case $flag in
        O)
            opts="-O"
            ;;
        o)
            opts="-o"
            ;;
        f)
            max_files=50
            ;;
        h)
            usage
            exit
            ;;
        \?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cat > $tmp_file 
n=`cat $tmp_file | wc -l`

if [ $n -gt $max_files ]; then
    echo "Too many files to edit: required $n while max is $max_files "
    exit
fi

#vim -p `cat $tmp_file` < /dev/tty
vim $opts `cat $tmp_file` < /dev/tty
