#!/bin/bash


if [ ! $# == 2 ]
then
    echo "Usage: do-prepare-release <ref-release> <release-name>"
    exit

fi


curr_path=$PWD
curr_folder=`basename $PWD`

if [ ! "$curr_folder" == "releases" ]
then
    echo "Not in releases folder"
    exit
fi

if [ ! -d "$1" ]
then
    echo "$1 does not exists"
    exit
fi

if [ -d "$2" ]
then
    echo "$2 already exists"
    exit
fi


cd $1
find . -type d -exec mkdir -p "$curr_path/$2/"{} \;

cd $curr_path

find $2
