#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

all=0
while getopts ha flag
do
    case $flag in
        a)
            all=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $all -eq 0 ]; then
    cat | sed "s/\"/\\\\\"/g" | sed "s/^/\"/" | sed "s/$/\"/"
else
    cat | sed "s/\"/\\\\\"/g" | sed "s/^/\"/" | sed "s/$/\"/"| do-pipe-trimmed -a | sed "s/ /\", \"/g"
fi
