#!/usr/bin/env bash

function usage()
{
    cmd=$(basename $0)
    echo "Usage: <pipe> | $cmd [-v] [<grep-pattern>]"
    echo "                      -v            : verbose"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

verbose=0
while getopts hv flag
do
    case $flag in
        v)
            verbose=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

filter_patt=""
if [ $# -gt 0 ]; then
    filter_patt="\|$1"
fi

if [ $verbose -eq 1 ]; then
    cat | grep -i "error:\|warning:\|\[CP\]\|\[GEN\]\|\[AR\]\|\[CC\]\|\[LD\]\|^===$filter_patt" #| tee build.log
else
    cat | grep -i "error:\|warning:\|\[AR\]\|\[CC\]\|\[LD\]$filter_patt"  #| tee build.log
fi
