#!/usr/bin/env bash


if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi


if [ ! $# -eq 2 ]; then
    echo "Usage: <text> | do-pipe-text-object <begin-pattern> <end-pattern>"
    exit
fi

text=$(cat)
cmd="echo \"$text\"| sed '/$1/,/$2/!d'"
eval "$cmd"
