#!/usr/bin/env bash
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h|--help] [<pdf-filename-pattern>]"
    echo "Examples:"
    echo "   $cmd   \"list\""
}


folders='.'

if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]
    then
        usage
        exit
    fi
    # TODO: improve filtering considering only the filename but maintaining the path
    ecmd="find $folders -maxdepth 3 -name \"*.pdf\" | \\grep \"$@\""
else
    ecmd="find $folders -maxdepth 3 -name \"*.pdf\" "
fi

num=`eval "$ecmd"|wc -l`
if [ "$num" == 1 ]
then
    ecmd="$ecmd|xargs -I@ mupdf @"
fi
echo "> $ecmd"
eval "$ecmd"&
