#!/usr/bin/env bash

function usage() {
    echo "Usage: <pipe> | do-pipe-uniq [-h] [-u]"
    echo "       where:"
    echo "                 -h            : print this help"
    echo "                 -u            : print only the unique input elements"
    echo "                 -c            : print also the number of occurences"
    echo "                 -d            : print only duplicated items"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Error: $cmd must be used in a pipe"
    usage
    exit
fi

opts=""
while getopts hucd flag
do
    case $flag in
        u)
            opts="$opts -u"
            ;;
        c)
            opts="$opts -c"
            ;;
        d)
            opts="$opts -d"
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


cat | sort | uniq $opts
