#!/bin/bash

function help() {
    cmd=`basename $0`
    echo "Usage: $cmd [<release-name> [<ref-release>]] "
}
if [  $# -gt 2 ]
then
    help
    exit

fi

if [ -z "$PROJECT" ]; then
    echo "Not in a project"
    exit
fi

rel_root=`echo /media/sf_Shared/releases/`
new_rel=$rel_root/$PROJECT
if [ $# -gt 0 ]; then
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]
    then
        help
        exit
    fi
    new_rel=$rel_root/$1
fi

if [ $# == 2 ]; then
    ref_rel=$rel_root/$2
    if [ ! -d "$ref_rel" ]
    then
        echo "$ref_rel does not exists"
        exit
    fi
fi


if [ -d "$new_rel" ]
then
    echo "$new_rel already exists"
    exit
fi

if [ $# == 2 ]; then
    cd $ref_rel
    find . -type d -exec mkdir -p "$new_rel/"{} \;

    cd $new_rel

    find 
else
    mkdir $new_rel
fi
