#!/usr/bin/env bash

# Check it is used correctly	
if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

cat | grep "^diff\|^+\s\+.*$1\|^-\s\+.*$1" | grep -B1 "^[+-]" | grep -v "^\-\-$" | grep --color "$\|$1"
