#!/usr/bin/env bash

function usage() {
    echo "Usage: <pipe> | do-pipe-uniq [-h] [-u]"
    echo "       where:"
    echo "                 -h            : print this help"
    echo "                 -u            : print only the unique input elements"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Error: $cmd must be used in a pipe"
    usage
    exit
fi

opts=""
while [ $# -gt 0 ]; do
    if [ "$1" == "-h" ]; then
        usage
        exit
    fi
    if [ "$1" == "-u" ]; then
        opts="$opts -u"
        shift
    fi
    if [ "$1" == "-c" ]; then
        opts="$opts -c"
        shift
    fi
done


cat | sort | uniq $opts
