#!/usr/bin/env bash

tag="Index:"
patchfile="/tmp/do-pipe-patched-files.tmp"
cat >  $patchfile

if [ $(cat $patchfile|grep "^diff --git"|wc -l) -gt 0 ]; then
	tag="diff --git"
fi


cat $patchfile | grep "^$tag"
