#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi


vcmd=":vnew"
while getopts hoOp flag
do
    case $flag in
        o)
            vcmd=":new"
            ;;
        O)
            vcmd=":vnew"
            ;;
        p)
            vcmd=":tabnew"
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cmds=""
for file in $@;
do
    if [ -f "$file" ]; then
        cmds="$cmds -c \"$vcmd $file\""
    fi
done


cmd="vim -R $cmds -"
eval "cat|$cmd"
