#!/usr/bin/env bash

text=0
if [ "$1" == "-t" ]; then
    text=1
fi
if [ $text -eq 1 ]; then
    cat | tr -d "\r" | sed "s/^\([^:]*\):\([0-9]*\):\(.*\)$/\1 \2 \[\[\3\]\]/"
else
    cat | tr -d "\r" | sed "s/^\([^:]*\):\([0-9]*\):.*$/\1 \2/"
fi
