#!/bin/bash

if [ ! $# == 1 ]
then
    app=`basename $0`
    echo "Usage: $app <file-to-redirect-output>"
    exit
fi

if [ -f "$1" ]
then
    echo "File $1 already exists"
    exit
fi

#do_something 2>&1 | tee -a some_file
cat 2>&1 | tee -a $1
