#!/bin/bash

cmd=`basename $0`

function usage() {
    echo "Usage: <piped-commands> | $cmd <output-file>"
}


if [ -t 0 ]; then
    usage
    exit
fi

if [ ! $# == 1 ]
then
    usage
    exit
fi

if [ -f "$1" ]
then
    echo "File $1 already exists"
    exit
fi

#do_something 2>&1 | tee -a some_file
# TODO: solve redirection issue - convert to command which evaluate the input pipe command
cat 2>&1 | tee -a $1
