#!/usr/bin/env bash

function usage() 
{
    cmd=`basename $0`
    echo "Usage: $cmd [-h] [-r] [-p]"
    echo "             -h          : this help"
    echo "             -r          : list releases tags"
    echo "             -p          : print full path"
}

subpath="tags"
paths=0
while getopts hrp flag
do
   case $flag in
      r)
         subpath="releases"
         ;;

      p)
         paths=1
         ;;
      q)
         quiet=1
         ;;
      h)
         usage
         exit
         ;;
      ?)
         usage
         exit
         ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument


filter="^"
if [ $# -gt 0 ]; then
   filter=$1
   shift
fi


repo=$(svn info 2>&1 | grep Root | grep Repo | do-pipe-columns 3)

if [ $repo == "" ]; then
    echo "Not in a Subversion working copy"
    exit
fi

branches="$repo/$subpath/"

if [ $paths -eq 0 ]; then
   svn ls $branches | sort -V | \grep --color "$filter"
else
   svn ls $branches | sort -V | sed "s#^#$branches#" | \grep --color "$filter"
fi
