#!/usr/bin/env bash

if [ "$1" == "-h" ]; then
    cmd=`basename $0`
    echo "Usage: $cmd [-b]"
    echo "          -b  Use byobu client"
    exit
fi

user=`whoami`
group=`groups $user | grep dialout`

sd=`which sudo`

cmd=
if [ -z "$group" ]; then
    cmd="do-super"
    if [ "$1" == "-b" ]; then
        cmd="do-super -H"
    fi
fi


if [ "$1" == "-b" ]; then
    cmd+=" byobu-"
fi

cmd+="screen -L /dev/ttyUSB0 38400,cs8,-ixon,-ixoff"

echo "> $cmd"
eval $cmd
