#!/usr/bin/env bash

#pipe input:             path/filename linenumber
#input parameters:       "pattern_to_replace" "replace_text"

function usage() {
    echo "Usage: <filename linenumber> | <cmd> <search-for> <replace-with>"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "$cmd must be used in a pipe"
    usage
    exit
fi

while getopts h flag
do
    case $flag in
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cat | while read filename linenumber;
do
    echo "$filename:$linenumber"; sed -i "${linenumber}s/$1/$2/" "$filename"
done
