#!/usr/bin/env bash

script="\n\
if [ -f $WDC_DO_COMMANDS_DIR/do_bash_customization ]; then\n\
\t. $WDC_DO_COMMANDS_DIR/do_bash_customization\n\
fi\n\
"

is_custom=`cat ~/.bashrc | grep -E "\. $WDC_DO_COMMANDS_DIR/do_bash_cust"`

if [ ! -z "$is_custom" ]; then
    echo "Customization already installed"
    exit
fi

echo -e $script >> ~/.bashrc
