#!/usr/bin/env bash

function usage() 
{
    cmd=`basename $0`
    echo "Usage: $cmd [-h] [-a]"
    echo "            -h            : this help"
    echo "            -a            : print all"

}

all=0

while getopts ha flag
do
   case $flag in
      a)
         all=1
         ;;
      q)
         quiet=1
         ;;
      h)
         usage
         exit
         ;;
      ?)
         usage
         exit
         ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cmd="svn status | grep -v \"^?\""
echo "> $cmd"
eval $cmd

if [ $all -eq 1 ]; then
   cmd="svn status | grep \"^?\""
   echo ""
   echo "# Untracked files:"
   echo ""
   echo "> $cmd"
   eval $cmd
fi
