#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd <user> <group>"
}

if [ ! $# == 2 ]; then
    usage
    exit
fi

do-super "usermod -a -G $2 $1"

groups $1

echo "WARNING: changes need to re-login in order to be applied"
