#!/usr/bin/env bash

function usage() 
{
    cmd=`basename $0`
    echo "Usage: $cmd [-h] [-f]"
    echo "            -h            : this help"
    echo "            -f            : force switch even with uncommited changes"

}

paths=0
all=0
force=0

while getopts hf flag
do
   case $flag in
      q)
         quiet=1
         ;;
      f)
         force=1
         ;;
      h)
         usage
         exit
         ;;
      ?)
         usage
         exit
         ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! -d .svn ]; then
   echo "Not in the root folder of a subversion repository"
   exit
fi

repo=$(svn info 2>&1 | grep Root | grep Repo | do-pipe-columns 3)
if [ $repo == "" ]; then
    echo "Not in a Subversion working copy"
    exit
fi

curr=$(svn info | grep "^URL" | do-pipe-columns 2)
trunk="$repo/trunk"

if [ "$curr" == "$trunk" ]; then
   echo "Already in the trunk"
   exit
fi

nc=$(svn status | grep "^M" | wc -l)
if [ $force -eq 0 ]; then
    if [ $nc -gt 0 ]; then
       echo "There are uncommitted changes"
       svn status | grep "^M"
       exit
    fi
fi

svn switch $trunk
