#!/usr/bin/env bash

function usage()
{
    cmd=$(basename $0)
    echo "Usage: $cmd [-q] [-f] [-r <revs-range>] [<files>]"
    echo "             -q                       : quiet"
    echo "             -f                       : print just the filenames"
    echo "             -r                       : print diff of the specified revs. range"
}


quiet=0
files=0
revs=""
while getopts hqfr: flag
do
    case $flag in
        q)
            quiet=1
            ;;
        r)
            revs=$OPTARG
            ;;
        f)
            files=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! -t 1 ]; then
    quiet=1
fi

if [ "$revs" == "" ]; then
    cmd="svn diff --patch-compatible -x --ignore-all-space $@"
else
    cmd="svn diff --patch-compatible -x --ignore-all-space -r $revs $@"
fi
if [ $files -eq 1 ]; then
    cmd="svn diff --patch-compatible -x --ignore-all-space --summarize -r $revs $@"
fi
if [ $quiet -eq 0 ]; then
   echo "> $cmd"
fi
eval $cmd
