#!/bin/bash

if [ -z "$TESTS" ]; then
    echo "TESTS not defined"
    exit
fi

if [ -z "$PROJECT" ]; then
    echo "PROJECT not defined"
    exit
fi

if [ ! -d "$TESTS/$PROJECT" ]; then
    mkdir "$TESTS/$PROJECT" && echo "Created folder $TESTS/$PROJECT"
fi

if [ ! $# == 1 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <test_name>"
    exit
fi

#curdate="`date '+%y%m%d-%H%M%S'`"
curdate=`date '+%y%m%d-%H%M'`
test_name="test_${curdate}_$1"
test_path=$TESTS/$PROJECT/$test_name

if [ -d "$test_path" ]; then
    echo "The test already exists: $test_name"
    exit
fi

mkdir $test_path&& echo "Created test: $test_name"
