#!/usr/bin/env bash

function usage() {
	cmd=$(basename $0)
	echo "Usage: $cmd [-o|-n] [-q] [-h]"
	echo "where:"
	echo "             -o             : remove old"
	echo "             -n             : remove new"
	echo "             -q             : quiet"
	echo "             -h             : help"
}


old=1
new=1
while getopts hqon flag
do
    case $flag in
        o)
            old=0
            ;;
        n)
            new=0
            ;;
        q)
            quiet=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $old -eq 0 ] && [ $new -eq 0 ]; then
    echo "Cannot remove both old and new lines"
    exit
fi

files=$(do-svn-status -p)
for file in $files;
do
    if [ -f $file ]; then
        svn cat $file > $file.tmp

        if [ $old -eq 1 ] && [ $new -eq 1 ]; then
            diff --unchanged-line-format="" --old-line-format="$file:%dn: %L" --new-line-format="$file:%dn: %L" $file $file.tmp | sort -t':' -k2,2 -n
        elif [ $old -eq 0 ]; then
            diff --unchanged-line-format="" --old-line-format="" --new-line-format="$file:%dn: %L" $file $file.tmp | sort -t':' -k2,2 -n
        elif [ $new -eq 0 ]; then
            diff --unchanged-line-format="" --old-line-format="$file:%dn: %L" --new-line-format="" $file $file.tmp | sort -t':' -k2,2 -n
        fi
        rm $file.tmp
    fi
done
