#!/usr/bin/env bash

quiet=0
while getopts hq flag
do
    case $flag in
        q)
            quiet=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -gt 0 ]; then
    url="$1"
else
    url=$(svn info|grep "^URL"|awk '{print $2}')
fi
b_logs=$(svn log --stop-on-copy -r0:HEAD $url)
b_revs=$(echo "$b_logs" |grep "^r[0-9]*"|awk '{print $1}'|tr -d 'r')
b_first=$(echo $b_revs| tr ' ' '\n' | head -1)
b_last=$(echo $b_revs| tr ' ' '\n' | tail -1)

cmd="svn diff -r$b_first:$b_last $url"
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval "$cmd"
