#!/usr/bin/env bash

function usage() 
{
    cmd=`basename $0`
    echo "Usage: $cmd [-h] [-f]"
    echo "            -h            : this help"
    echo "            -f            : force switch even with uncommited changes"
    echo "            -n            : no execute command"
    echo "            -r            : revision to switch to"
}

paths=0
all=0
force=0
dryrun=0
rev=0

while getopts hfnr: flag
do
   case $flag in
      r)
         rev=$OPTARG
         ;;
      n)
         dryrun=1
         ;;
      q)
         quiet=1
         ;;
      f)
         force=1
         ;;
      h)
         usage
         exit
         ;;
      ?)
         usage
         exit
         ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! -d .svn ]; then
   echo "Not in the root folder of a subversion repository"
   exit
fi

repo=$(svn info 2>&1 | grep Root | grep Repo | do-pipe-columns 3)
if [ $repo == "" ]; then
    echo "Not in a Subversion working copy"
    exit
fi

curr=$(svn info | grep "^URL" | do-pipe-columns 2)

if [ -z $SVN_TRUNK ]; then
    SVN_TRUNK=trunk
fi

trunk="$repo/$SVN_TRUNK"

if [ "$curr" == "$trunk" ]; then
   echo "Already in the trunk"
   exit
fi

nc=$(svn status | grep "^M" | wc -l)
if [ $force -eq 0 ]; then
    if [ $nc -gt 0 ]; then
       echo "There are uncommitted changes"
       svn status | grep "^M"
       exit
    fi
fi

if [ $rev -eq 0 ]; then
    cmd="svn switch $trunk"
else
    cmd="svn switch -r $rev $trunk"
fi
echo "> $cmd"
if [ $dryrun -eq 0 ]; then
    eval "$cmd"
fi
