#!/usr/bin/env bash

unameOut="$(uname -s)"
case "${unameOut}" in
	Linux*)     machine=Linux;;
	Darwin*)    machine=Mac;;
	CYGWIN*)    machine=Cygwin;;
	MINGW*)     machine=MinGw;;
	*)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}

if [ $machine == "MinGw" ]; then
	exit
fi

check=`which inxi`

if [ -z $check ]; then
    uname -a
    file /usr/bin/file | awk '{ print $3 " GNU/Linux " $18 }'
    cat /proc/meminfo | head -2
    df -lh --output="size,used,target"
    exit
fi

inxi -c 13 -b
