#!/usr/bin/env bash

function usage() 
{
    cmd=`basename $0`
    echo "Usage: $cmd [-h] [-p] [-a]"
    echo "            -h            : this help"
    echo "            -p            : print full path"
    echo "            -a            : print all branches"

}

paths=0
all=0

while getopts hap flag
do
   case $flag in
      a)
         all=1
         ;;

      p)
         paths=1
         ;;
      q)
         quiet=1
         ;;
      h)
         usage
         exit
         ;;
      ?)
         usage
         exit
         ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

filter="^"
if [ $# -gt 0 ]; then
   filter=$1
   shift
fi

repo=$(svn info 2>&1 | grep Root | grep Repo | do-pipe-columns 3)
if [ "$repo" == "" ]; then
    echo "Not in a Subversion working copy"
    exit
fi

branches="$repo/branches/"
if [ ! -z $SVN_USER ]; then
   branches="$repo/branches/$SVN_USER/"
fi

if [ $all -eq 1 ]; then
   branches="$repo/branches/"
fi


if [ $filter == "^" ]; then
   echo "Repository: $repo"
   echo "User:       $SVN_USER"
   echo ""
fi
if [ $paths -eq 0 ]; then
   svn ls $branches | \grep --color "$filter"
else
   svn ls $branches | sed "s#^#$branches#" | \grep --color "$filter"
fi
