#!/bin/bash

if [ ! $# == 1 ]
then
    cmd=`basename $0`
    echo "Usage: $cmd <initramfs_dir>"
    exit
fi

if [ ! -d $1 ]
then
    echo "$1 is not a folder"
    exit
fi

if [ ! -z "$PROJECT" ]; then
    common=`echo ~/linux/$PROJECT/lib/modules`
else
    common=`echo ~/linux/lib/modules`
fi

if [ ! -d "$common" ];then
    mkdir -p $common
fi

modules=`ls -1 $common|head -1`

if [ -z "$modules" ]
then
    echo "Missing modules in $common"
    exit
fi


echo "Update $1/lib/modules with $modules {Y/N}?"
read answer
if [ "$answer" == "Y" ]
then
    echo "Updating modules..."
    install_dir="$1/lib/modules"
    if [ -d "$install_dir" ]
    then
        rm -rf "$install_dir"
    fi
    mkdir -p "$install_dir"

    cp -r $common/$modules $install_dir
    echo "Done"
    find $install_dir
fi

