#!/usr/bin/env bash

if [ ! $# == 1 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <tar-archive>"
    exit
fi

if [ ! -f "$1" ]; then
    echo "Error: missing file $1"
    exit
fi


# check extension: tar.bz2, tar.gz
cmd="tar"
ext=".tar.gz"
opt="zf"
check=`echo $1 | grep $ext`
if [ -z "$check" ]; then
    ext=".tar.bz2"
    opt="jf"
    check=`echo $1 | grep $ext`
    if [ -z "$check" ]; then
        cmd="unzip"
        ext=".zip"
        opt=""
        check=`echo $1 | grep $ext`
        if [ -z "$check" ]; then
            echo "Error: unknow extension"
            exit
        fi
    fi
fi

file=${1%$ext}


$cmd -t${opt} "$1" | head -20

#TODO: check if a folder will be created

echo "..."

read -p "Untar? <y|n>" ans


if [ $ans == "y" ] || [ $ans == "Y" ]; then
    # check if destination folder already exists
    folder=`tar -t${opt}f "$1" | head -1`
    if [ -d "$folder" ]; then
        echo "Error: $folder already exists"
        exit
    fi

    if [ $cmd=="tar" ]; then
        $cmd -x${opt} "$1"
    else
        if [ $cmd=="unzip" ]; then
            $cmd ${opt} "$1"
        fi
    fi

    # TODO: cd into the untarred folder
fi

