#!/bin/sh

if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ]
    then
        cmd=`basename $0`
        echo "Usage: $cmd <files>"
        return
    fi
fi

if [ ! -z "$RELEASE" ]
then
    release=$RELEASE
else
    release=$PROJECT
fi

if [ -z "$release" ]
then
    release=`basename $PWD`
fi

echo "Release: $release"

orig="/media/sf_Shared/releases/$release"
dest="."

if [ ! -d "$orig" ]
then
    echo "Missing release folder $orig"
    exit
fi

do-find-release -type f | sed "s#$orig/##" | do-numerate | more
echo "File to update? "
read num

file=`do-find-release -type f | do-numerate | grep "$num" | awk '{ print $2 }'`
filename=`basename "$file"`
if [ -f "$filename" ]
then
    echo "Coping $file ..."
    echo "Are you sure to update: $filename {Y/N}?"
    read answer
    if [ "$answer" != "Y" ]
    then
        return
    fi
fi

cp $file $dest
ls -last $dest | head -10
