#!/usr/bin/env bash


# TODO: improve check to see if we are in the root of the linux kernel
file=MAINTAINERS
if [ ! -f $file ]
then
    echo "Not in the Linux kernel root folder"
    exit
fi

if [ ! -z "$PROJECT" ]; then
    common=`echo ~/linux/$PROJECT`
else
    common=`echo ~/linux`
fi

if [ ! -d "$common" ];then
    mkdir -p $common
fi

modules=`ls -1 "$common/lib/modules"|head -1`

if [ ! -z "$modules" ]
then
    echo "Replace $common/lib/modules/$modules {Y/N}?"
    read answer
    if [ ! "$answer" == "Y" ]
    then
        exit
    fi
    rm -rf $common
    mkdir -p $common
fi

echo "Updating modules..."
export INSTALL_MOD_PATH="$common"
make modules && make modules_install

# remove links to the folder used to build the modules
for file in  `find $common`
do
    if [ -h "$file" ]
    then
        rm "$file"
    fi
done
find "$common/lib/modules/$modules"
echo "Done"
