#!/bin/sh

#TODO: use only two inout <path/filename> <other-root-path>

if [ ! $# -eq 3 ]
then
    app=`basename $0`
    echo "Usage: $app <root1> <root2> <common-path>"
    exit
fi

vimdiff --noplugin $1/$3 $2/$3
