#!/usr/bin/env bash


# Support Functions 
yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }


# Usage help function
cmd=`basename $0`

function usage() {
  echo "Usage: $cmd [-h] [-t|T <task_name>|.] [-r] [-O|-o|-p] [<file>..]"
  echo "where:"
  echo "       -h                          : print this help"
  echo "       -t|T <task>                 : start/continue work on <task> (-T for global)"
  echo "       -t|T -                      : continue work on last used <task> (-T for global)"
  echo "       -t|T .                      : select task to start/continue work on (-T for global)"
  echo "       -r                          : reset session about the <task>"
  echo "       -O|-o|-p                    : vim visualization mode"
}

# Arguments processing
task=""
vimopt=""
session_reset=0
global=0
while getopts ht:T:oOpr flag
do
  case $flag in
    r)
      session_reset=1
      ;;
    p)
      vimopt="-p"
      ;;
    O)
      vimopt="-O"
      ;;
    o)
      vimopt="-o"
      ;;
    T)
      task="$OPTARG"
      [ "$task" == "" ] && task="."
      global=1
      ;;
    t)
      task="$OPTARG"
      [ "$task" == "" ] && task="."
      global=0
      ;;
    h)
      usage
      exit
      ;;
    ?)
      usage
      exit
      ;;
  esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

function list_tasks() {
  (echo "NEW"; 
  (ls -1 "$OBSESSIONS_PATH" | grep "^task_.*\.vim$"| sed 's/^task_\(.*\)\.vim/\1/';
  ls -1 "$NOTEBOOKS_PATH" | grep "^task_.*\.nb$"| sed 's/^task_\(.*\)\.nb/\1/';) | sort | uniq) | awk '{ printf "%-2s %-60s\n", NR, $0 }' | column -t
}


if [ ! "$task" == "" ]; then
  if [ $global -eq 0 ]; then
    OBSESSIONS_PATH="$PROJECT_PATH/.obsessions"
    [ "$PROJECT_PATH" == "" ] && OBSESSIONS_PATH="$HOME/.obsessions"
    NOTEBOOKS_PATH="$PROJECT_PATH/.notebooks"
    [ "$PROJECT_PATH" == "" ] && NOTEBOOKS_PATH="$HOME/.notebooks"
  else
    OBSESSIONS_PATH="$HOME/.obsessions"
    NOTEBOOKS_PATH="$HOME/.notebooks"
  fi
  [ ! -d "$OBSESSIONS_PATH" ] && mkdir -p "$OBSESSIONS_PATH"
  [ ! -d "$NOTEBOOKS_PATH" ] && mkdir -p "$NOTEBOOKS_PATH"

  if [ "$task" == "." ]; then
    list_tasks
    read -p "task? " num

    if [ "$num" == "" ]; then
        exit
    fi
    if [ "$num" == "1" ]; then
      read -p "task name? " task
      task_name="task_$(echo "$task"| tr ' ' '_' | sed 's/^task_//')"
      task_filename="${task_name}.vim"
    else
      task_name="task_$(list_tasks|grep "^$num "|sed 's/[ \t]\+/ /g'|cut -d' ' -f2)"
      task_filename="${task_name}.vim"
    fi
  elif [ "$task" == "-" ]; then
    task_name=$(ls -t $OBSESSIONS_PATH | grep "task_" | head -1 | sed 's#^\(task_.*\)\.vim$#\1#')
    task_filename="${task_name}.vim"
  elif [ $(echo "$task" | grep "^[0-9]\+$" | wc -l) -gt 0 ]; then
    num="$task"
    task="."
    [ $num -eq 1 ] && list_tasks && exit
    [ $(list_tasks|grep -c "^$num ") -eq 0 ] && echo "Wrong task id" && exit
    task_name="task_$(list_tasks|grep "^$num "|sed 's/[ \t]\+/ /g'|cut -d' ' -f2)"
    task_filename="${task_name}.vim"
  else
    task_name="task_${task}"
    task_filename="${task_name}.vim"
  fi
  task_path="$OBSESSIONS_PATH/${task_filename}"
  nb_cmd="VimNotebookOpen"
  [ $global -eq 1 ] && nb_cmd="VimNotebookOpenGlobal" 
  if [ -f "$task_path" ]; then
    [ $session_reset -eq 1 ] && rm -f "$task_path"
    cmd="\vi -S \"$task_path\" -c \":silent Obsession $task_path\" -c \":$nb_cmd $task_name\" $vimopt $@"
  else
    cmd="\vi -c \":silent Obsession $task_path\" -c \":$nb_cmd $task_name\" $vimopt $@"
  fi
  echo "> $cmd"
  eval "$cmd"
  exit
fi

\vi "$vimopt" $@
