#!/usr/bin/env bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

prj_root=`echo /media/sf_Shared/releases/`
n=0
if [ $# == "1" ]
then
    n=`ls -1 $prj_root | grep $1 | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root | grep $1 | awk '{ print NR, $0 }'
else
    n=`ls -1 $prj_root | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root | awk '{ print NR, $0 }'
fi

num=-1
if [ "$n" == "0" ]
then
    echo "Project/s not found!!!"
    return
fi

if [ "$n" == "1" ]
then
    num=1
else
    read -p "Project Num: " num
fi


if [ $# == 1 ]
then
    prj=`ls -1 $prj_root | grep $1 | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
else
    prj=`ls -1 $prj_root | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
fi

export RELEASE="$prj"
export RELEASE_PATH="/media/sf_Shared/releases/$prj"

echo "RELEASE=$RELEASE"

if [ ! -d "$RELEASE_PATH" ]
then
    echo "WARNING -  missing release path: $RELEASE_PATH"
fi
