#!/bin/bash

force_color_prompt=yes


export TESTS=~/tests
export PROJECTS=~/projects
export SHARED_FOLDER=/media/sf_Shared

# to use vim keybindings in bash, 
# do "set -o vi". Then, you can 
# press "v" to edit current command 
# in vim.
#set -o vi
echo "Customizing bash"

function cd_folder()
{
   # check it is present the # symbol, otherwise use the standard cd command
   echo "WARNING: STILL UNDER DEVELOPMENT"
}

function edit_last()
{
cmd=`history |grep "^[0-9]* *vi "|tail -1|sed "s/^[0-9]* *//"`
echo "> $cmd"
eval $cmd
}

# spinner got from http://fitnr.com/showing-a-bash-spinner.html
# When you have a task to run that will take a large (or unknown) amount of time invoke it in a background subshell like this:
# 
# (a_long_running_task) &
# 
# Then, immediately following that invocation, call the spinner and pass it the PID of the subshell you invoked.
# 
# spinner $!
# 
# The $! is a bash internal variable for the PID of the last job run in the background. 
#
# TODO: evaluate pv (pipe viewer) command
#
function spinner()
{
    local pid=$1
    local delay=0.175
    local spinstr='|/-\'
    tput civis;
    local infotext=$2
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c] %s" "$spinstr" "$infotext"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
        for i in $(seq 1 ${#infotext}); do
            printf "\b"
        done
    done
    printf " \b\b\b\b"
    tput cnorm;
}
alias spinner='sleep 3 && spinner $! "Doing something big..."'

function make()
{
  # see http://stackoverflow.com/questions/6436563/how-can-i-highlight-the-warning-and-error-lines-int-the-make-output

  #pathpat="(/[^/]*)+:[0-9]+"
  pathpat="^.*$"
  ccred=$(echo -e "\033[0;31m")
  ccgreen=$(echo -e "\033[0;32m")
  ccyellow=$(echo -e "\033[0;33m")
  ccend=$(echo -e "\033[0m")
  /usr/bin/make "$@" 2>&1 | sed -E \
      -e "/^cc/ s%$pathpat%$ccgreen&$ccend%g" \
      -e "/[Ee]rror:/ s%$pathpat%$ccred&$ccend%g" \
      -e "/[Uu]ndefined reference to/ s%$pathpat%$ccred&$ccend%g" \
      -e "/core dumped/ s%$pathpat%$ccred&$ccend%g" \
      -e "/[Ww]arning:/ s%$pathpat%$ccyellow&$ccend%g"
  return ${PIPESTATUS[0]}
}

function vim_launcher() {
opts=""
if [ $# -eq 1 ]; then
    if [ -f "$1" ]; then
        n=`cat "$1" | wc -l`
        if [ $n -gt 5000 ]; then
            opts="--noplugin $1"
            shift
        fi
    else
        if [ -d "$1" ]; then
            opts="$1"
            shift
        fi
    fi
fi

for opt in $@
do
    if [ -f "$opt" ]; then
        if [ `file "$opt" | grep -o executable` ]; then
            # make sure it is a binary file
            if [ ! `file "$opt" | grep -o text` ]; then
                for file in `ls "$opt".*| grep -v "\.sav$"`
                do
                    if [ `file "$file" | grep -o text` ]; then
                        opts="$opts -p $file"
                    fi
                done
                continue
            fi
        fi
    else
        n=0
        for file in `ls "$opt"*|grep -v ".sav$"`
        do
                    if [ `file "$file" | grep -o text` ]; then
                        opts="$opts -p $file"
                        n=$((n+1))
                    fi
        done
        if [ $n -gt 0 ]; then
            continue
        fi
    fi
    opts="$opts $opt"
done
cmd="vim --servername wdcvimsrvr $opts"
echo "> $cmd"
eval $cmd
}


#. ~/bin/do_setup_env_for_okl4sdk-5.1.8m4
#. ~/bin/do_setup_env okl4sdk-5.1.8m4
. ~/bin/do_setup_env 

function mkcd() {
    mkdir "$1"
    cd "$1"
}
function mterm() {
    #xfce4-terminal --geometry=80x20
    xterm -fn 10x20
}
function cdenv() {
    if [ $1 == "?" ]; then
       env | grep "PROJECT_ROOT" | sort | grep --color "PROJECT_ROOT[0-9]*"
       return
    fi
    if [ $1 == "-" ]; then
       \cd -
       return
    fi
    # TODO: evaluate to replace this with smartcd tool
    NEW_PATH=$1
    if [ -z "${1##[0-9]*}" ]; then
       PROJECT_ROOT=$(eval "echo \$$(echo PROJECT_ROOT${1})")
       if [ ! -z $PROJECT_ROOT ]; then
          PROJECT_ROOT=$PROJECT_PATH/$PROJECT_ROOT
          if [ -d "$PROJECT_ROOT" ]; then
             NEW_PATH="$PROJECT_ROOT"
          fi
       fi
    fi
    if [ ! -d $NEW_PATH ]; then
       echo "Missing folder: $NEW_PATH"
       return
    fi

    \cd $NEW_PATH
    pwd
    if [ -f .bash_env ]
    then
        cat .bash_env
        source .bash_env
    else
        shift $#
        . ~/bin/do_setup_env
    fi
}
function setup_env() {
    if [ -f .bash_env ]; then
        . .bash_env
    fi
}
function gohome() {
    # find upword the following: .git, project folder, user home
    if [ $# -gt 0 ]
    then
        if [ "$1" == "-h" ]
        then
            echo "Usage: gh [-p|-u]"
            echo "       where:"
            echo "               -p       : go to project home"
            echo "               -u       : go to user home"
            return
        fi
        if [ "$1" == "-p" ]; then
           \cd $PROJECT_PATH 
           setup_env
           return
        fi
        if [ "$1" == "-u" ]; then
            \cd `echo ~`
            setup_env
            return
        fi
    fi

    path=`dirname $PWD`
    folder=`basename $PWD`
    if [ $folder == "/" ]
    then
        return
    fi
    if [ $folder == "$user" ]
    then
        path="/"
        echo "$path"
        \cd `echo $path`
        setup_env
        return
    fi
    found=0
    user=`whoami`
    while [ $found -eq 0 ]
    do
        folder=`basename $path`
        parent=`dirname $path`
        parent_folder=`basename $parent`

        #echo $path
        #echo $folder
        #echo $parent
        if [ $folder == "$user" ] ||
            [ -d "$path/.git" ] ||
            [ -h "$path/.git" ] ||
            [ -d "$path/.svn" ] ||
            [ -h "$path/.svn" ] ||
            [ -d "$path/src" ] ||
            [ -f "$path/.bash_env" ] ||
            [ -d "$parent/$folder.git" ] ||
            [ "$parent_folder" == "projects" ] ||
            [ "$parent_folder" == "releases" ] ||
            [ "$parent_folder" == "tests" ] ||
            [ $folder == "/" ] 
        then
            found=1
        else
            path=$parent
        fi
    done
    echo "$path"
    \cd `echo $path`
    ls
    setup_env
}

function last() {
    opts="-1t"
    quiet=0
    if [ $# -gt 0 ]
    then
        if [ "$1" == "-h" ]
        then
            echo "Usage: last [-q|-p|-s|-l|<ls-options>] [<path>]"
            echo "       where:"
            echo "               -q       : quiet"
            echo "               -p       : like -1dt"
            echo "               -s       : like -1sht"
            echo "               -l       : like -last"
            return
        fi
        if [ "$1" == "-q" ]
        then
            quiet=1
            shift
        fi
        if [ "$1" == "-p" ]
        then
            shift
            p="."
            if [ $# -gt 0 ]; then
                p="$1"
            fi
            if [ $quiet -eq 0 ]; then
                echo "> ls -1dt $p/* | head -20"
            fi
            ls -1dt $p/* | head -20
            return
        fi
        if [ "$1" == "-s" ]
        then
            opts="-1sht"
            shift
        fi
        if [ "$1" == "-l" ]
        then
            opts="-last"
            shift
        fi
    fi
    #ls -last $@ | head -20
    cmd="ls $opts $@ 2>/dev/null | head -20"

    if [ $quiet -eq 0 ]; then
        echo "> $cmd"
    fi
    eval $cmd
}

function do_activate_release() {
    script=`echo ~/bin/do_activate_release`
    source $script
}

function copy_and_cd()
{
    if [ "$#" -ne 2 ];
    then
        echo "Usage: cac <file> <dest-folder>"
        return
    fi
    if [ -d "$2" ];
    then
        cp $1 $2
        cd $2
    fi
}
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function prompt_command()
{
    export TYPE=`pwd | sed -e "s/\// /g" | awk '{ print $3}'`
    # if [ "$TYPE" = "projects" ];
    # then
    #     TYPE="p"
    # fi
    export PROJECT=""
    case $TYPE in
        "projects")
            TYPE="p"
            PROJECT=`pwd | sed -e "s/\// /g" | awk '{ print $4}'`
            ;;
        "tests")
            TYPE="t"
            PROJECT=`pwd | sed -e "s/\// /g" | awk '{ print $4}'`
            ;;
        "releases")
            TYPE="r"
            PROJECT=`pwd | sed -e "s/\// /g" | awk '{ print $4}'`
            ;;
    esac

    export PROJECT_PATH=`echo ~/projects/$PROJECT`
    export TEST_PATH=`echo ~/tests/$PROJECT`
    export RELEASE_PATH=`echo ~/releases/$PROJECT`
    export LOCATION=`basename $PWD`
    if [ "$PROJECT_PATH" == $PWD ]
    then
        LOCATION=""
    fi
    if [ "$TEST_PATH" == $PWD ]
    then
        LOCATION=""
    fi
    if [ "$RELEASE_PATH" == $PWD ]
    then
        LOCATION=""
    fi
    history -a; history -c; history -r
}
PROMPT_COMMAND=prompt_command
#export PS1="\[\033[00m\]\u@\h\[\033[01;34m\] \W \[\033[31m\]\$(parse_git_branch) \[\033[00m\]$\[\033[00m\] "
#if [ "$color_prompt" = yes ]; then
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    #PS1='\[\033[01;32m\]$TYPE\[\033[00m\]:\[\033[01;31m\]$PROJECT\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
    PS1='\t:\[\033[01;32m\]$TYPE\[\033[00m\]:\[\033[01;31m\]$PROJECT\[\033[00m\]:\[\033[01;34m\]$LOCATION\[\033[00m\]\$ '
else
    #PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    #PS1='`basename \w` \$ '
    #PS1='$TYPE:$PROJECT:\W \$ '
    PS1='\t:$TYPE:$PROJECT:$LOCATION \$ '
fi


alias do-bash-customization='. ~/bin/do_bash_customization'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='\ls --color=auto'
    alias lf='\ls -1 | grep -v "sav$" | tr "\n" " " ; echo'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

#alias vi='vim --servername wdcvimsrvr'
alias vi='vim_launcher $@'
alias vinp='vim --noplugin $@'

alias cac="copy_and_cd $@"
#alias last="last $@"
alias last=last


#alias term='xfce4-terminal --geometry=100x40'
alias term='xterm -maximized -fn 10x20&'
#alias miniterm='xfce4-terminal --geometry=80x20'
alias miniterm='xterm -fn 10x10&'

alias cd-p='cd ~/projects/$PROJECT'

alias cd-projects='cd ~/projects/'
alias cd-tests='cd ~/tests/'
alias cd-releases='cd /media/sf_Shared/releases/'

alias do-create-project='. ~/bin/do_create_project'
alias do-cd-test='. ~/bin/do_cd_test'
alias do-cd-release='. ~/bin/do_cd_release'
alias do-cd-folder='. ~/bin/do_cd_folder'
alias do-cd-path='. ~/bin/do_cd_path'
alias do-cd-bookmark='. ~/bin/do_cd_bookmark'
alias do-cd-link='. ~/bin/do_cd_link'

alias do-bookmark-list='do-cd-bookmark -l'

alias cd=cdenv 
alias gh=gohome
alias do-activate-project='. ~/bin/do_activate_project'
alias do-activate-release='. ~/bin/do_activate_release'
alias do-activate-test='. ~/bin/do_activate_test'
alias do-setup-env='. ~/bin/do_setup_env -s'
alias do-setup-ld-library-path='. ~/bin/do_setup_ld_library_path $@'

alias do-history-update='. ~/bin/do_history_update'
alias do-history-add-last='. ~/bin/do_history_add_last'
alias do-history-diagram='. ~/bin/do_history_diagram'

alias mkca='make clean all'
alias mka='make all'

alias do-edit-last='edit_last'

alias do-git-conf-author-wdc='do-git-conf-author "Walter Di Carlo" walter@di-carlo.it'

# default proxy setup
export http_proxy=
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"

if [ -f ~/bin/do_proxy_setup ]; then
    source  ~/bin/do_proxy_setup
    echo "http_proxy=$http_proxy"
    echo "https_proxy=$https_proxy"
    echo "ftp_proxy=$ftp_proxy"
    echo "rsync_proxy=$rsync_proxy"
    echo "no_proxy=$no_proxy"
fi
