#!/bin/bash

prj_root=`echo ~/.bookmarks`
n=0
if [ $# == 1 ]
then
    n=`cat $prj_root | grep $1 | awk '{ print NR, $0 }' | wc -l`
    cat $prj_root | grep $1 | awk '{ print NR, $0 }'
else
    n=`cat $prj_root | awk '{ print NR, $0 }' | wc -l`
    cat $prj_root | awk '{ print NR, $0 }'
fi

num=-1
if [ "$n" == 0 ]
then
    echo "Bookmark/s not found!!!"
    return
fi

if [ "$n" == 1 ]
then
    num=1
else
    read -p "Bookmark Num: " num
fi


if [ $# == 1 ]
then
    prj=`cat $prj_root | grep $1 | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
else
    prj=`cat $prj_root | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
fi

cd "${prj}"
if [ ! -f .bash_env ]; then
    shift $#
    . ~/bin/do_setup_env
fi
