#!/usr/bin/env bash

if [ ! $# == 1 ]
then
    cmd=`basename $0`
    echo "Usage: $cmd <path>"
    return
fi


folder="$1"
if [ -f "$1" ]
then
    folder=`dirname $1`
fi


if [ ! -d "$folder" ]
then
    echo "The folder $folder does not exists"
    return
fi
cd $folder
