#!/usr/bin/env bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

#cmd=`basename $0`
cmd="do-cd-path"

if [ ! $# == 1 ]
then
    echo "Usage: $cmd <path>"
    return
fi


folder="$1"
if [ -f "$1" ]
then
    folder=`dirname $1`
fi


if [ ! -d "$folder" ]
then
    echo "The folder $folder does not exists"
    return
fi
cd $folder
