#!/usr/bin/env bash

prj_root=`echo /media/sf_Shared/tests/`

n=0
if [ $# == 1 ]
then
    n=`ls -1 $prj_root | grep $1 | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root | grep $1 | awk '{ print NR, $0 }'
else
    n=`ls -1 $prj_root | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root | awk '{ print NR, $0 }'
fi

num=-1
if [ "$n" == 0 ]
then
    echo "Test/s not found!!!"
    return
fi

if [ "$n" == 1 ]
then
    num=1
else
    read -p "Test Num: " num
fi

num="$num "
if [ $# == 1 ]
then
    prj=`ls -1 $prj_root | grep $1 | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
else
    prj=`ls -1 $prj_root | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
fi

cd "${prj_root}$prj"
