#!/usr/bin/env bash

#cmd=`basename $0`
cpath=`pwd`


function usage() {
    echo "Usage: do-cd-bookmark [-g] [-l] [-a] [-t] [-s] [<string>]"
    echo "         where:"
    echo "                  -g                 : globals - do not restrict to current project"
#echo "       -b                 : just consider the basename"
    echo "                  -s                 : input is a tag"
    echo "                  -l                 : list bookmarks"
    echo "                  -a                 : returns absolute paths"
    echo "                  -t                 : print the available tags"
    return
}


# TODO: use getopts

global="0"
list="0"
absolute="0"
tags="0"
symbol="0"

while [ $# -gt 0 ]; do
    if [ "$1" == "-h" ]; then
        usage
        return
    fi
    if [ "$1" == "-g" ]; then
        global="1"
    fi

    if [ "$1" == "-a" ]; then
        absolute="1"
    fi

    if [ "$1" == "-l" ]; then
        list="1"
    fi
    if [ "$1" == "-t" ]; then
        tags="1"
    fi

    if [ "$1" == "-s" ]; then
        symbol="1"
    fi

    #if [ ! "${1:0,1}" == "-" ]; then
    if [ ! "$1" == "-h" ] && [ ! "$1" == "-l" ] && [ ! "$1" == "-a" ] && [ ! "$1" == "-g" ] && [ ! "$1" == "-s" ]; then
        break
    fi
    shift
done

bookmarks_file=`echo ~/.bookmarks`


if [ ! -f $bookmarks_file ]; then
    echo "No Bookmark/s not found!!!"
    return
fi

if [ $tags == "1" ]; then
    if [ "$PROJECT" == "" ]; then
        cat $bookmarks_file | xargs -I@ sh -c "echo \"@\"" | grep -v $PROJECT_PATH | grep " # " | sed "s/^.*#//" | tr " " "\n"|grep -v "^$"|sort|uniq|tr "\n" " "; echo
    else
        cat $bookmarks_file | xargs -I@ sh -c "echo \"@\"" | grep $PROJECT_PATH | grep " # " | sed "s/^.*#//" | tr " " "\n"|grep -v "^$"|sort|uniq|tr "\n" " "; echo
    fi
    return
fi


if [ "$PROJECT" == "" ]; then
    relpath=`echo $cpath|sed "s#$HOME/##"`
    global="1"
else
    relpath=`echo $cpath|sed "s#$PROJECT_PATH/##"`
fi


postproc="cat"
if [ $absolute == "0" ]; then
    if [ $global == "0" ]; then
        postproc="sed \"s#$PROJECT_PATH/##\""
    else
        postproc="sed \"s#$HOME/##\""
    fi
fi

bookmarks=""

if [ $global == "0" ]; then
    #bookmarks=`cat $bookmarks_file | grep $PROJECT_PATH/ | xargs -I@ sh -c "if [ -d @ ]; then echo @; fi"| sed "s#$PROJECT_PATH/##"`
    #bookmarks=`cat $bookmarks_file | grep $PROJECT_PATH/ | awk -F"#" '/1/2 { if( !system("test -d " $1) ){if (length($2)>0){printf "%-50s # %-30s\n",$1,$2}else{print $1} } }'| sed "s#$PROJECT_PATH/##"`
    bookmarks=`cat $bookmarks_file | xargs -I@ sh -c "echo \"@\"" | grep $PROJECT_PATH/ | awk -F"#" '/1/2 { if( !system("test -d " $1) ){if (length($2)>0){printf "%-50s # %-30s\n",$1,$2}else{print $1} } }'| eval $postproc`
else
    # TODO: allows jump into another project's folder by evaluating its .bash_env file
    #bookmarks=`cat $bookmarks_file | grep -v $PROJECTS | awk -F"#" '/1/2 { if( !system("test -d " $1) ){if (length($2)>0){printf "%-50s # %-30s\n",$1,$2}else{print $1} } }'`
    #bookmarks=`cat $bookmarks_file | grep -v $PROJECTS | awk -F"#" '/1/2 { if( !system("test -d " $1) ){if (length($2)>0){printf "%-50s # %-30s\n",$1,$2}else{print $1} } }'| sed "s#$HOME/##"`
    bookmarks=`cat $bookmarks_file | xargs -I@ sh -c "echo \"@\"" | grep -v $PROJECTS | awk -F"#" '/1/2 { if( !system("test -d " $1) ){if (length($2)>0){printf "%-50s # %-30s\n",$1,$2}else{print $1} } }'| eval $postproc`
fi

patt=$1
if [ $symbol == "1" ]; then
   patt="#.*$1"
fi
if [ "$list" == "1" ]; then
    if [ $# -gt 0 ]; then
        echo "$bookmarks"| grep $patt | grep --color "^\|$relpath *$\|$relpath *#.*"
    else
        echo "$bookmarks"| grep --color "^\|$relpath *$\|$relpath *#.*"
    fi
    return
fi

num=-1
# TODO: priority to filenames
#folders=`echo $bookmarks | xargs -I@ basename @`
#m=0
#if [ $# == 1 ]
#then
#    m=`echo "$folders" | grep $1 | awk '{ printf "%-2s %-60s\n", NR, $0 }' | wc -l`
#    if [ "$m" -gt 0 ]
#    then
#        if [ "$m" == 1 ]
#        then
#            num=1
#        fi
#
#    fi
#fi

n=0
if [ $# == 1 ]
then
    n=`echo "$bookmarks" | grep $patt | awk '{ printf "%-2s %-60s\n", NR, $0 }' | wc -l`
    echo "$bookmarks" | grep $patt | awk '{ printf "%-2s %-60s\n", NR, $0 }'| grep --color "^\|$relpath *$\|$relpath *#.*"
else
    n=`echo "$bookmarks" | awk '{ printf "%-2s %-60s\n", NR, $0 }' | wc -l`
    echo "$bookmarks" | awk '{ printf "%-2s %-60s\n", NR, $0 }'| grep --color "^\|$relpath *$\|$relpath *#.*"
fi

if [ "$n" == 0 ]
then
    echo "Bookmark/s not found!!!"
    return
fi

if [ "$n" == 1 ]
then
    num=1
else
    read -p "Bookmark Num: " num
fi

if [ "$num" == "" ]; then
    return
fi

if [ $# == 1 ]
then
    bpath=`echo "$bookmarks" | grep $patt | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
else
    bpath=`echo "$bookmarks" | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
fi

if [ $global == "0" ]; then
    cd "$PROJECT_PATH/${bpath}"
else
    cd "$HOME/${bpath}"
fi

# TODO: apply destination project env
if [ ! -f .bash_env ]; then
    shift $#
    . ~/bin/do_setup_env
fi
