#!/usr/bin/env bash


if [ ! $#  -gt 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <projectname> [<env>]"
    return
fi

if [ -z "$PROJECTS" ]; then
    echo "PROJECTS not defined"
    return
fi

if [ -d "$PROJECTS/$1" ]; then
    echo "Project already exists"
    return
fi

env_root=`echo ~/bin`
if [ $# -gt 1 ]; then
    env="$2"
    n=`ls -1 $env_root/do_setup_env_for_* | grep $env | wc -l`
    if [ $n -eq 1 ]; then
        mkdir "$PROJECTS/$1"
        echo "do-setup-env $env" > "$PROJECTS/$1/.bash_env"
    else 
        if [ $n -gt 1 ]; then
            echo "Specified ambiguous environment name"
            ls -1 $env_root/do_setup_env_for_* | sed "s#$env_root/do_setup_env_for_##"| grep $env
        else
            echo "Specified missing environment name"
            echo "Available environment name:"
            ls -1 $env_root/do_setup_env_for_* | sed "s#$env_root/do_setup_env_for_##"
        fi
        return
    fi
else
    mkdir "$PROJECTS/$1"
fi


source ~/bin/do_activate_project $1
