#!/usr/bin/env bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

if [ ! $# == 1 ]
then
    echo "Usage: do-cd-link <link>"
    return
fi


if [ ! -h "$1" ]
then
    echo "$1 is not a link"
    return
fi


# TODO: use the readlink -f command
folder=`file $1 | tr -d "\'" | awk '{print $5}'`
#folder=${folder:1}
if [ -f "$folder" ]
then
    folder=$(dirname $folder)
fi
if [ ! -d "$folder" ]
then
    echo "The folder $folder does not exists"
    return
fi
cd $folder
