#!/usr/bin/env bash

usage() 
{
    cmd=`basename $0`
    echo "Usage: $cmd <folder-name-grep-pattern>"
}

prj_root=`pwd`
n=0
maxdepth=5
if [ $# == 1 ]
then
    n=`find $prj_root -maxdepth $maxdepth -type d -name "*$1*" | awk '{ print NR, $0 }' | wc -l`
    find $prj_root -maxdepth $maxdepth -type d -name "*$1*" | awk '{ print NR, $0 }'
else
    usage
    return
fi

num=-1
if [ "$n" == 0 ]
then
    echo "Folder/s not found!!!"
    return
fi

if [ "$n" == 1 ]
then
    num=1
else
    read -p "Folder Num: " num
fi

if [ "$num" == "" ]; then
    return
fi

if [ $# == 1 ]
then
    prj=`find $prj_root -maxdepth $maxdepth -type d -name "*$1*" | awk '{ print NR, $0 }' |grep "^$num"|awk '{print $2}'`
fi
cd "$prj"
if [ ! -f .bash_env ]; then
    shift $#
    . $WDC_DO_COMMANDS_DIR/do_setup_env
fi
