#!/usr/bin/env bash
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

# To run the container with pandashells:
# docker run -i -v <host_path_to_plots>:/mnt/plots nate/pandashells p.<command>

[ "$PANDAS_MOUNT_POINT" == "" ] && echo "PANDAS_MOUNT_POINT not defined" && return

cmds="p.example_data p.df p.merge p.plot p.facet_grid p.hist"
for cmd in $(echo $cmds)
do
  command="\
function $(echo $cmd) () { \
  docker run -i -v $PANDAS_MOUNT_POINT:/mnt/plots nate/pandashells $cmd \"\$@\"; \
}; \
export -f $(echo $cmd)\
"
  echo "function $cmd"
  eval "$command"
done


