#!/usr/bin/env  bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

[ "$1" == "-h" ] && echo "do-project-activation [-h] [<project_name_pattern>]" && return

# shellcheck disable=SC2116
prj_root=$(echo "$PROJECTS/")
n=0
if [ $# == 1 ]
then
    n=$(ls -1 "$prj_root" | grep "$1" | awk '{ print NR, $0 }' | wc -l)
    ls -1 "$prj_root" | grep "$1" | awk '{ print NR, $0 }'| grep "^\|$1\|$PROJECT"
else
    n=$(ls -1 "$prj_root" | awk '{ print NR, $0 }' | wc -l)
    ls -1 "$prj_root" | awk '{ print NR, $0 }'| grep "^\|$PROJECT"
fi

num=-1
if [ "$n" -eq 0 ]
then
    echo "Project/s not found!!!"
    return
fi

if [ "$n" -eq 1 ]
then
    num=1
else
    read -p "Project Num: " num
fi


if [ "$num" == "" ]; then
    return
fi

if [ $# -eq 1 ]
then
    prj=$(ls -1 "$prj_root" | grep "$1" | awk '{print NR,$0}'|grep "^$num "|awk '{print $2}')
else
    prj=$(ls -1 "$prj_root" | awk '{print NR,$0}'|grep "^$num "|awk '{print $2}')
fi

cd "${prj_root}$prj" || return
if [ ! -f .bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit_env ]; then
    shift $#
    source "$WDC_DO_COMMANDS_DIR/do_setup_env"
fi

# set title of terminal window
echo -ne "\033]0;$prj\007"
