#!/usr/bin/env bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

# minimal PATH setup
# PATH=$WDC_DO_COMMANDS_DIR:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:.

function setup_project_env() {
    export INSTALL_MOD_PATH=~/linux

    export ARCH=arm

    export TOOLCHAIN=arm-none-eabi
    export CROSS_COMPILE=$TOOLCHAIN-

    # reset PATH
    PATH=$WDC_DO_COMMANDS_DIR:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:.


    PATH=$PATH:/opt/$TOOLCHAIN/bin

    export PROJECT_VARS="INSTALL_MOD_PATH ARCH TOOLCHAIN CROSS_COMPILE PATH"
}
