#!/usr/bin/env bash

# minimal PATH setup
# PATH=$WDC_DO_COMMANDS_DIR:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/bin:.

function setup_project_env() {
    # reset PATH
    PATH=$WDC_DO_COMMANDS_DIR:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/bin:.

    export PROJECT_VARS="PATH"
}
