#!/bin/bash


if [ $# == 0 ]; then
    is_project_folder=`pwd|grep $PROJECTS`
    if [ -z "$is_project_folder" ];then
        . ~/bin/do_setup_env empty
    else
        curr_folder=`basename $PWD`
        if [ -f "$PROJECTS/$curr_folder" ]; then
            . ~/bin/do_setup_env okl4sdk-5.1.8m4
        fi
    fi
    unset is_project_folder
    return
fi

list=0
if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ]
    then
        app=`basename $0`
        echo "Usage: $app [<find options>]"
        exit
    fi
    if [ "$1" == "-s" ]; then
        shift
    fi
    if [ "$1" == "-l" ]; then
        list=1
        shift
    fi
fi

prj_root=`echo ~/bin`
export PROJECT_VARS=""

if [ $list -eq 1 ]; then
    if [ $# == 1 ]
    then
        ls -1 $prj_root/do_setup_env_for_* | grep $1 | awk '{ print NR, $0 }' | sed "s#$prj_root/do_setup_env_for_##"
    else
        ls -1 $prj_root/do_setup_env_for_* | awk '{ print NR, $0 }' | sed "s#$prj_root/do_setup_env_for_##"
    fi
    return
fi

n=0
if [ $# == 1 ]
then
    if [ "$PROJECT_ENV" == "$1" ]; then
        return
    fi
    n=`ls -1 $prj_root/do_setup_env_for_* | grep $1 | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root/do_setup_env_for_* | grep $1 | awk '{ print NR, $0 }' | sed "s#$prj_root/do_setup_env_for_##"
else
    n=`ls -1 $prj_root/do_setup_env_for_* | awk '{ print NR, $0 }' | wc -l`
    ls -1 $prj_root/do_setup_env_for_* | awk '{ print NR, $0 }' | sed "s#$prj_root/do_setup_env_for_##"
fi

num=-1
if [ "$n" == 0 ]
then
    echo "Environment/s not found!!!"
    return
fi

if [ "$n" == 1 ]
then
    num=1
else
    read -p "Environment Num: " num
    if [ -z "$num" ]; then
        return
    fi
fi


if [ $# == 1 ]
then
    prj=`ls -1 $prj_root/do_setup_env_for_* | grep $1 | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
else
    prj=`ls -1 $prj_root/do_setup_env_for_* | awk '{print NR,$0}'|grep "^$num"|awk '{print $2}'`
fi

# TODO: check if the file $prj contains the function setup_project_env
env_path=`basename $prj`
env_name=${env_path#do_setup_env_for_}
if [ "$env_name" == "$PROJECT_ENV" ]; then
    return
fi

# reset environment 
PATH=~/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:.
PROJECT_VARS=
export PROJECT_ENV=$env_name
echo "Applying settings: $PROJECT_ENV"
. "$prj"
setup_project_env

if [ -z "$PROJECT_VARS" ]; then
    echo "WARNING: PROJECT_VARS not defined"
else
    for VAR in $PROJECT_VARS 
    do
        eval echo "$VAR=\$$VAR"
    done
fi

if [ -z "$PROJECT_ENV" ]; then
    echo "WARNING: PROJECT_ENV not defined"
else
    echo "PROJECT_ENV=$PROJECT_ENV"
fi
