#!/bin/bash

# minimal PATH setup
# PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:.

function setup_project_env() {
    export INSTALL_MOD_PATH=~/linux

    export ARCH=arm

    export TOOLCHAIN=arm-none-eabi
    export CROSS_COMPILE=$TOOLCHAIN-

    # reset PATH
    PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:.


    PATH=$PATH:/opt/$TOOLCHAIN/bin

    export PROJECT_VARS="INSTALL_MOD_PATH ARCH TOOLCHAIN CROSS_COMPILE PATH"
}
