#!/usr/bin/env bash

cmd=$(basename $0)

function usage() {
	echo "Usage: $cmd [-h] [-l] <link> [..<link>]"
}

if [ $# == 0 ]; then
    usage
    exit
fi

list=0
while getopts hl flag
do
    case $flag in
        l)
	    list=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

function list() {
	echo "$1 -> $2"
}

general_ans=c
function unlink() {
	if [ ! $# -eq 2 ]; then
		echo "Wrong parameters: $@"
		return
	fi

	echo "Unlinking: $1 -> $2"
	read -p "Are you sure to unlink $1? [y/n/a=all/e=exit]" ans

	if [ "$ans" == "e" ]; then
		exit
	fi
	if [ "$ans" == "y" ]; then
		rm $1
		cp $2 $1
	fi
}

function unlink_forced() {
	if [ ! $# -eq 2 ]; then
		echo "Wrong parameters: $@"
		return
	fi

	echo "Unlinking: $1 -> $2"

	rm $1
	cp $2 $1
}

# TODO: use unlink
apply="unlink_forced" 
if [ $list -eq 1 ]; then
	apply="list"
fi
for FILE in $@; do
	#file $FILE | sed "s/[:'\`]//g" | awk '{print $1 " " $5 }' | while read a b; do echo "$a -> $b"; done
	file $FILE | sed "s/[:'\`]//g" | awk '{print $1 " " $5 }' | while read a b; do $apply $a $b; done
done
