#!/usr/bin/env bash


LUAROCKS_ROOT=~/.luarocks
LUAROCKS_CONFIG=${LUAROCKS_ROOT}/config.lua


if [ ! -f $LUAROCKS_CONFIG ]; then
    mkdir -p $LUAROCKS_ROOT
    cat > $LUAROCKS_CONFIG <<LUAROCKS_CONFIG
           rocks_servers={
              "http://luarocks.giga.puc-rio.br/";
           }
LUAROCKS_CONFIG
fi

if [ -f $LUAROCKS_ROOT/bin/luarocks ]; then
    cmd=$LUAROCKS_ROOT/bin/luarocks
else
    cmd=`which luarocks`
    if [ "$cmd" == ""  ]; then
        echo "Missing luarocks command"
        exit
    fi
fi


if [ $# == 0 ]; then
    $cmd --tree=`echo $LUAROCKS_ROOT` | less
else
    $cmd --tree=`echo $LUAROCKS_ROOT` $@
fi
