#!/usr/bin/env bash


if [ ! $# -eq 2 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd <encryptped-folder> <decrypted-folder>"
    exit

fi

cmd=`which encfs`
if [ -z "$cmd" ]; then
    echo "Missing encfs command, please install encfs package"
    exit
fi

src=`echo $(cd $(dirname $1); pwd)/$(basename $1)`
dst=`echo $(cd $(dirname $2); pwd)/$(basename $2)`

# mount encrypted folde, use absolute paths
encfs $src $dst
