#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-a] [-e <path> [-e <path>]]  <folder> [<post-fix>]"
    echo "Where:"
    echo "            -a               : all files"
    echo "            -e <path>        : exclude <path>"
}

quiet=0
all=0
exclude=""
while getopts haqe: flag
do
    case $flag in
        e)
            exclude="$exclude --exclude=$OPTARG"
            ;;
        q)
            quiet=1
            ;;
        a)
            [ $all -eq 0 ] && all=1 && exclude="$exclude --exclude=.git --exclude=.svn --exclude=initramfs --exclude=initramfs_dbg --exclude=*.boot"
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [[ $# < 1 || $# > 2 ]]
then
    usage
    exit
fi


if [ ! -d "$1" ]
then
    echo "Missing folder $1"
    exit
fi

folder_path=`echo ${1%/}`
filename=`basename $folder_path`
curdate="`date '+%y%m%d-%H%M%S'`"

if [ $2 ]; then
	tarfile="$filename-$curdate-$2.tar.bz2"
else
	tarfile="$filename-$curdate.tar.bz2"
fi


cmd="tar -cjf ${tarfile} ${exclude}  ${folder_path}/"
echo "> $cmd"
eval $cmd
