#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    if [ ! -d "$1" ]; then
        echo "Not a valid folder: $1"
        exit 1
    fi  
    filenames=$(do-find-files -r "$1" "*.txt" | sort -r)
else
    filenames=$(do-find-files "*.txt" | sort -r)
fi


names=$(echo "$filenames" | sed 's/_[0-9]*\.txt//' | grep -v "\.txt" | uniq)

files=""
for name in $names;
do
	file=$(echo "$filenames" | grep "${name}_[0-9]*\.txt" | head -1)
	files=$(printf "%s\n%s" "$files" "$file")
done
others=$(do-find-files "*_[0-9]*_*.txt" | sort -r)
files="$files $others"
echo "$files" | sort -r
