#!/usr/bin/env bash

if [ ! -f ".config" ]
then
    echo "Missing .config file"
    exit
fi
# grep NAME .config
# grep CUSTOM_PATH .config
grep -e CUSTOM_PATH -e HOSTNAME -e LOCALVERSION -e _PLAT_ -e _ARCH_ -e BOARD .config| grep -vE "^#"
