#!/usr/bin/env bash

cmd=`basename $0`

function usage() {
	echo "Usage: $cmd [-h] [-p <num_pages>] [-q] [-n] [-i <num_items_per_pages>] [-s <sec_to_sleep>] <project_id>>"
	echo "where:"
	echo "       -s <sec_to_sleep>           : seconds to sleep after each request"
	echo "       -i <num_items_per_pages>    : number of items per page to retrieve"
	echo "       -p <num_pages>              : number of pages to retrieve"
	echo "       -h                          : print this help"
	echo "       -q                          : quiet"
	echo "       -n                          : dry run"
}


quiet=0
dryrun=0
pages=1
items=20
seconds=0
while getopts hqnp:i:s: flag
do
	case $flag in
		s)
			seconds=$OPTARG
			;;
		i)
			items=$OPTARG
			;;
		p)
			pages=$OPTARG
			;;
		n)
			dryrun=1
			;;
		q)
			quiet=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -eq 0 ]; then
    echo "Missing project id"
    exit 1
fi

if [ "$GITLAB_SERVER" == "" ]; then
    echo "GITLAB_SERVER not defined"
    exit
fi

if [ "$GITLAB_GROUPID" == "" ]; then
    echo "GITLAB_GROUPID not defined"
    exit
fi

if [ "$TOKEN" == "" ]; then
    echo "Missing TOKEN value"
    exit
fi

token="PRIVATE-TOKEN: $TOKEN"
url_projects="https://$GITLAB_SERVER/api/v4/projects"
projectid="$1"

opts=""
if [ $quiet -eq 1 ]; then
    opts="-sS"
fi

concatenate=0
if [ $pages -gt 1 ]; then
    concatenate=1
    echo "["
fi
# jq --argjson arr1 "$firstArr" --argjson arr2 "$secondArr" -n '$arr2 + $arr1' # this is failing
for counter in $(seq 1 $pages);
do
    cmd="curl $opts --header \"$token\" \"$url_projects/$projectid/merge_requests?state=merged&page=$counter&per_page=$items&scope=all\""
    if [ $quiet -eq 0 ]; then
       echo "> $cmd"
    fi
    if [ $dryrun -eq 0 ]; then
        if [ $concatenate -eq 0 ]; then
           eval "$cmd | jq ."
        else
           if [ $counter -lt $pages ]; then
               eval "$cmd | jq . | grep -v \"^\[\|^]\" | head -n -1" # remove last 1 lines, i.e. }
               echo "   },"
           else
               eval "$cmd | jq . | grep -v \"^\[\|^]\""
           fi
        fi
    fi
    if [ $counter -lt $pages ] && [ $seconds -gt 0 ]; then
        if [ $quiet -eq 0 ]; then
           echo "waiting $seconds secs..."
        fi

        sleep $seconds
    fi
done
if [ $dryrun -eq 0 ]; then
    if [ $concatenate -eq 1 ]; then
        echo "]"
    fi
fi

