#!/usr/bin/env bash
# Usage help function
cmd=`basename $0`

function usage() {
   echo "Usage: $cmd [-h] [-l] [<path>]"
   echo "where:"
   echo "       -l                          : less is more"
   echo "       -h                          : print this help"
}

# Arguments processing
doless=0
while getopts hl flag
do
case $flag in
  l)
      doless=1
      ;;
  h)
      usage
      exit
      ;;
  ?)
      usage
      exit
      ;;
   esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ "$1" == "" ]; then
    DIR="."
else
    DIR="$1"
fi

#find "$DIR" -type f -exec grep -Il . {} \; | xargs -I@ sh -c "echo @;cat @|head"
find "$DIR" -type f -exec grep -Il . {} \; | while read -r file
do
    name=$(basename $file)
    echo "$file"
    if [ ${file: -4} == ".csv" ]; then
        cat "$file" | do-pipe-table-prettyprinted | head -25
    elif [ ${file: -5} == ".json" ]; then
        cat "$file" | jq '.' | head -15
    else
        cat "$file" | head -10
    fi | sed 's/^/\t/' 
done | ( [ $doless -eq 0 ] && cat || less )

