#!/usr/bin/env bash
#

filter="$@"

if [ $# -eq 0 ]; then
    filter="$"
fi
[ "$WDC_DO_COMMANDS_DIR" == "" ] && echo "Missing WDC_DO_COMMANDS_DIR" && exit

cd "$WDC_DO_COMMANDS_DIR" 
find * -type f | grep "do[-_]" | grep -v "\.sav" | \grep --color "$filter"
