#!/usr/bin/env bash
#

# Usage help function
cmd=`basename $0`

function usage() {
    echo "Usage: $cmd [-h] [-q] [-f] [-c] [-a] [-o] [-t] [-r <root>] [-p] <string>"
    echo "where:"
    echo "       -h                          : print this help"
    echo "       -f                          : find the filenames"
    echo "       -c                          : find in all commands (even not versioned)"
    echo "       -a                          : find in all files (even not versioned)"
    echo "       -o                          : find only in the options"
    echo "       -r                          : find in the <root> folder"
    echo "       -t                          : find only in the howto files"
    echo "       -p                          : print absolute paths"
    echo "       -q                          : quiet"
}

# Arguments processing
quiet=0
all=0
options=0
files=0
root="$WDC_DO_COMMANDS_DIR"
filter="do[-_]"
apaths=0
while getopts hqaocfr:tp flag
do
    case $flag in
	t)
      filter="howto_"
	    ;;
	r)
      root="$OPTARG"
	    ;;
	p)
	    apaths=1
	    ;;
	o)
	    options=1
	    ;;
	f)
	    files=1
	    ;;
	c)
	    all=1
	    ;;
	a)
	    all=2
	    ;;
	q)
	    quiet=1
	    ;;
	h)
	    usage
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# == 0 ]; then
    usage
    exit
fi

root=$(echo "$root"| sed 's#\(.*\)\/$#\1#') # remove trailing slash
[ ! -d "$root" ] && echo "Wrong command folder: $root" && exit

cd "$root"
cmd="git ls-files | grep \"^${filter}.*\\\|/${filter}.*\""
if [ $all -eq 1 ]; then
    cmd="find . -maxdepth 2 -type f -name \"${filter}*\" | sed 's#^\.\/##'"
elif [ $all -eq 2 ]; then
    cmd="find . -not -path \"./.git/*\" -type f | sed 's#^\.\/##'"
fi

pars="$@"

[ $apaths -eq 1 ] && cmd="$cmd | sed \"s#^#$root/#\""

if [ $files -eq 1 ]; then
    cmd="$cmd | grep $pars"
else
    if [ $options -eq 0 ]; then
        cmd="$cmd | xargs -I@ sh -c \"\grep --color -Hn \\\"$pars\\\" @\""
    else
        cmd="$cmd | xargs -I@ grep -Hn \"getopts.*h\" @ |sed 's/^\([a-z/-]*\):.*/\1/'|sort|uniq|xargs -I@ sh -c \"@ -h\"| \grep --color \"${filter}[a-z_-]*\|$pars\""
    fi
fi

# Quieting command output
if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
