#!/usr/bin/env bash

bin_dir=$(echo "$WDC_DO_COMMANDS_DIR")

function usage() {
    echo "Usage: $cmd [-f] <new-bin-cmd>"
    echo "where:"
    echo "            -f          : add file (default add command)"
}

quiet=0
file=0
while getopts hqf flag
do
	case $flag in
		q)
			quiet=1
			;;
		f)
			file=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cd "$bin_dir"

if [ ! $# -eq 1 ]; then
    usage
    exit
fi

dfile="$1"

if [ ! -f "$dfile" ]; then
    echo "Missing file in $bin_dir/$dfile"
    exit
fi

[ $(echo $dfile|grep -c "do[-_]\|howto_") -eq 0 ] && echo "Wrong filename" && exit
[ $(git ls-files | grep -c "$dfile$") -eq 1 ] && echo "Command/file already included in git" && exit

git add $dfile
if [ $file -eq 0 ]; then
	git commit -m "Added $dfile command"
else
	git commit -m "Added $dfile file"
fi
