#!/usr/bin/env bash

root="$WDC_DO_COMMANDS_BIN"

[ ! -d "$root" ] && echo "Wrong command folder: $root" && exit

func=0
[ "$1" == "-f" ] && func=1

# do_setup_env -s
declare -A cmds
#cmds["do_setup_env"]="-s"
cmds["do_bash_customization"]="&& cd ."
cmds["do_setup_ld_library_path"]="\$@"
ls -1 "$root"| grep "^do_" | grep -v "\." | while read -r file
do 
  args="${cmds[$file]}"
  [ "$1" == "-l" ] && echo "$file"|tr '_' '-' && continue
  if [ $func -eq 0 ]; then
    echo "alias $(echo $file|tr '_' '-')='source \$WDC_DO_COMMANDS_BIN/$file $args'" | sed "s/ '$/'/"
  else
    cat << EOF
function $(echo $file|tr '_' '-') () {
  source \$WDC_DO_COMMANDS_BIN/$file $args
}
export -f $(echo $file|tr '_' '-')
EOF
  fi
done
