#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd <do-command-name-pattern>"
    echo "Examples:"
    echo "   $cmd   \"do-cmd-update\""
}

if [ $# -ne 1 ]
then
    usage
    exit
fi
folders=$(echo "$WDC_DO_COMMANDS_DIR/")

if [ $# == 1 ]
then
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]
    then
        usage
        exit
    fi
    # TODO: improve filtering considering only the filename but maintaining the path
    list=$(find $folders -type f | grep "do[_-].*" | grep "$@" | grep -v "\.sav$")
    num=`ls -1 $list|wc -l`
    if [ "$num" -lt 10 ]
    then
        vim -p `echo $list` < `tty` 
    else
        ls -1 $list
    fi
else
    find $folders -type f  | grep "^do[_-].*"
fi

