#!/usr/bin/env bash

bin_dir=`echo $WDC_DO_COMMANDS_DIR`


function usage() {
    echo "Usage: $cmd [-f] [-r] [-m \"message\"] <improved-bin-cmd>"
    echo "where:"
    echo "            -f          : update file (defualt update command)"
    echo "            -r          : avoid review of changes before to update"
    echo "            -m          : message to append to the standard message"
}

quiet=0
file=0
review=1
message=""
while getopts hqfrm: flag
do
	case $flag in
		m)
			message="$OPTARG"
			;;
		r)
			review=0
			;;
		q)
			quiet=1
			;;
		f)
			file=1
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

cd $bin_dir


if [ ! $# -eq 1 ]; then
    usage
    exit
fi

if [ ! -f $1 ]; then
    echo "Missing file in $bin_dir/$1"
    exit
fi

cmd="$1"

[ $(file $cmd|grep -c "shell script") -eq 0 ] && echo "Not a script, please provide the relative path to the script" && exit 

# TODO: check if the command is already present in the git repository
# check if the command has changes
n=`git diff $1 | wc -l`
if [ $n -eq 0 ]; then
    echo "Command without changes: $1"
    exit
fi

if [ $review -eq 1 ]; then
	do-git-diff -q $1 | do-pipe-to-vim -o $1
    read -p "Do you Accept the Changes? <Yy|n> (Y to specify a commit message) " ans
	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
    [ "$ans" == "Y" ] && echo "Message? [$msg]" && read -p "" message
		echo "Changes accepted!!!"
	else
		exit
	fi
fi

git add $1

msg=""
if [ $file -eq 0 ]; then
    msg="Improved $1 command."
else
    msg="Update $1 file."
fi

[ ! "$message" == "" ] && msg="$msg ${message^}"

git commit -m "$msg"
