#!/usr/bin/env bash

# Usage help function
cmd=$(basename ${BASH_SOURCE[0]})

function usage() {
  echo "Usage: $cmd [-h] <-l|<file..>>"
  echo "where:"
  echo "       -h                          : print this help"
  echo "       -l                          : list destination folder"
}

# Arguments processing for sources script
list=0
while getopts hl flag
do
  case $flag in
    l)
      list=1
      ;;
    h)
      usage
      exit
      ;;
    ?)
      usage
      exit
      ;;
  esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ "$PUBLISH_DIR" == "" ]; then
  echo "Missing PUBLISH_DIR"
  exit 1
fi

[ $list -eq 1 ] && echo "$PUBLISH_DIR:" && ls -l "$PUBLISH_DIR" && exit

if [ $# -eq 0 ]; then
  echo "Missing file/s to publish"
  usage
  exit
fi

if [ ! -d "$PUBLISH_DIR" ]; then
  echo "Not a folder: $PUBLISH_DIR"
  exit 1
fi

for file in "$@"
do
  if [ ! -f "$file" ]; then
    echo "Skipping $file"
    continue
  fi
  cmd="cp \"$file\" \"$PUBLISH_DIR\""
  echo "> $cmd"
  eval "$cmd"
  ls -lh "${PUBLISH_DIR}/$(basename ${file})"
done
