#!/usr/bin/env bash

function usage()
{
    cmd=$(basename $0)
    echo "Usage: $cmd [-i] [-e]"
    echo "             -i             : edit ignore property"
    echo "             -e             : edit externals property"
}

ignore=0
externals=0
while getopts hie flag
do
    case $flag in
        i)
            ignore=1
            ;;
        e)
            externals=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $ignore -eq 1 ]; then
    echo "Edit ignore property"
    svn propedit svn:ignore .
fi

if [ $externals -eq 1 ]; then
    echo "Edit externals property"
    svn propedit svn:externals .
fi

