#!/usr/bin/env bash
folders=`echo $WDC_DO_COMMANDS_DIR`

if [ $# == 1 ]
then
    if [ "$1" == "-h" ] || [ "$1" == "--help" ]
    then
        cmd=`basename $0`
        echo "Usage: $cmd <do-command-command-pattern"
        echo "Examples:"
        echo "   $cmd   \"linux\""
        exit
    fi
    # TODO: improve filtering considering only the filename but maintaining the path
    if [ -f "$folders/howto_$1.otl" ]; then
        vim "$folders/howto_$1.otl" < `tty`
        exit
    fi

    list=`find $folders/ -name "howto_*$1*\.otl"`
    num=`ls -1 $list|wc -l`
    if [ "$num" == 1 ]
    then
        vim `echo $list` < `tty` 
    else
        do-howto-list | grep $1
    fi
else
    do-howto-list 
fi

