#!/usr/bin/env bash

[ "$WDC_DO_COMMANDS_HOWTO_DIR" == "" ] && echo "Missing WDC_DO_COMMANDS_HOWTO_DIR" && exit

if [ ! $# == 3 ]
then
    cmd=`basename $0`
   echo "Usage: $cmd <category> \"title\" \"command\""
   echo "       where <category> may be:"
   echo "          git"
   echo "          linux"
   echo "          debian"
   echo "          ..."
   exit
fi

howto=`echo $WDC_DO_COMMANDS_HOWTO_DIR/howto_$1.otl`

if [ ! -f $howto ]; then
    echo "Missing howto file: $howto"
    exit
fi

echo -e "$2\n\t$3" >> $howto

cat $howto | tail

