#!/bin/sh


#if [ $# == 1 && "$1" == "-h" ]
#then
#        app=`basename $0`
#        echo "Usage: $app [<find options>]"
#        exit
#fi

if [ -z "$TEST_PATH" ]
then
    echo "Variable \$TEST_PATH not defined"
    exit
fi

test_path=$TEST_PATH

if [ ! -z "$TEST" ]
then
    test_path=$TEST_PATH/$TEST
fi


if [ ! -d "$test_path" ]
then
    echo "Missing test folder $test_path"
    exit
fi
find $test_path $@
