#!/usr/bin/env bash


if [ ! $# == 2 ]
then
    cmd=`basename $0`
   echo "Usage: $cmd \"title\" \"command\""
   exit
fi

howto=`echo $WDC_DO_COMMANDS_HOWTO_DIR/howto_debian.otl`

echo -e "$1\n\t$2" >> $howto

cat $howto | tail



