#!/usr/bin/env bash

function usage() {
    echo "Usage: do-pipe-folders-paths [-e] [-p] [-h] [-q]"
    echo "Default: Filter out paths ending with /"
    echo "where:"
    echo "       -q                 : quiet"
    echo "       -e                 : list paths containing files"
    echo "       -p                 : print absolute paths"
    echo "       -h                 : print this help"
}

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

absolute=0
empty=1
quiet=0
while getopts qeph flag
do
    case $flag in

        q)
            quiet=1
            ;;
        e)
            empty=0
            ;;
        p)
            absolute=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ ! $# -eq 0 ]; then
    usage
    exit
fi

postproc=""
if [ $absolute -eq 1 ]; then
    postproc=" | sed 's#^./##' | xargs -I@ echo $(cd $(dirname @); pwd)/$(basename @)"
fi

empty_proc="| grep \"\/$\""
if [ $empty -eq 0 ]; then
    empty_proc=" | xargs -I@ dirname @"
fi

cmd="cat $empty_proc | sort | uniq $postproc"

if [ $quiet -eq 0 ]; then
    echo "> $cmd"
fi
eval $cmd
