#!/usr/bin/env bash


if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

if [ $# -ne 1 ]; then
    echo "Usage: <pipe> | do-pipe-splitted-words <char>"
    exit
fi


cat | sed "s/\($1\)/ \1/g"
