#!/usr/bin/env bash

function usage() {
    cmd=`basename $0`
    echo "Usage: $cmd [-r <root_ref>] <patch_name_without_spaces>"
    echo "             -r <root_ref>              : use patch name <root_ref>-<curdate>-<patch_name>.diff"
}

if [ -t 0 ]; then
    usage
    echo ""
    echo "ATTENTION: $cmd must be used in a pipe"
    exit
fi

if [ -z $PATCHES_DIR ]; then
    echo "PATCHES_DIR not defined"
    exit
fi

curdate="`date '+%y%m%d-%H%M%S'`"
verbose=0
root=$(basename `pwd`)
while getopts hvr: flag
do
    case $flag in
        r)
            root=$OPTARG
            ;;
        v)
            verbose=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -eq 0 ]; then
    usage
    exit
fi

postfix="$@" # TODO replace white spaces with _
file="$PATCHES_DIR/$root-$curdate-$postfix.diff"

if [ $verbose -eq 0 ]; then
    cat > $file
else
    cat | tee $file
fi
num_patched=$(cat $file|grep "^Index\|^diff"|wc -l)
echo "Created patch: $file"
echo "Patched files: $num_patched"
cat $file|grep "^Index"|sed "s/^Index: //"
