#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

# echo -n do not print newline
# TODO: put line numbers in the same column
# TODO: sort by num of lines/filename
cat | xargs -I@ sh -c "echo -n \"@ \";cat @ | wc -l"
