#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    echo "            which generate a list of"
    echo "            files suitable for cfile"
    echo "                <path1>:<n1>:<comment1>"
    echo "                <path2>:<n2>:<comment2>"
    echo "                <path3>:<n3>:<comment3>"
    exit
fi


cat | grep "^.*:[0-9]*: *.*" > "$HOME/.vim/vim_cfile.txt"

if [ $(cat ~/.vim/vim_cfile.txt | head -1 | wc -l) -eq 1 ]; then
    cmd="\vim -c \"cfile $HOME/.vim/vim_cfile.txt\" -c \"copen\""

    if [ $# == 1 ]; then
        cmd="$cmd -c \"let @/=\\\"$1\\\"\""
    fi
    cmd="$cmd -"

    echo "> $cmd"
    eval $cmd
fi

