#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "$cmd must be used in a pipe"
    exit
fi


if [ $# -lt 2 ]; then
    echo "Usage: <list> | do-pipe-map <key-pattern> <value-pattern>"
    exit
fi

missing=0
while getopts h flag
do
    case $flag in
        m)
            missing=1
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

key_patt=$1
val_patt=$2


cat | grep ".*$key_patt.*$val_patt" | sed "s/.*\($key_patt\).*\($val_patt\).*/\1 \2/" | awk '{ printf "%-60s %-60s\n", $1, $2}'
