#!/usr/bin/env bash

if [ -t 0 ]; then
    cmd=`basename $0`
    echo "Usage: $cmd must be used in a pipe"
    exit
fi

function usage() {
    echo "Usage: <cmds> | do-pipe-text-blocks \"<begin-text-block-pattern>\" \"<end-text-block-pattern>\""
}

if [ ! $# -eq 2 ]; then
    usage
    exit
fi

# text=$(cat)
# cmd="echo \"$text\"| sed '/$1/,/$2/!d'"
# eval "$cmd"
cat | sed -e '/$1/,/$2/!d'
