#!/usr/bin/env bash
[[ ${BASH_SOURCE[0]} == ${0} ]] && echo "$(basename ${BASH_SOURCE[0]}) must be sourced" && exit

# minimal PATH setup
# PATH=$HOME/.arkade/bin:$WDC_DO_COMMANDS_BIN:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/bin:.:$HOME/go/bin:$HOME/nbin:$HOME/node_modules/.bin:/snap/bin:$HOME/.krew/bin:$HOME/.fzf/bin

function setup_project_env() {
    export INSTALL_MOD_PATH=~/linux

    export ARCH=arm

    export TOOLCHAIN=arm-none-eabi
    export CROSS_COMPILE=$TOOLCHAIN-

    # reset PATH
    PATH=$HOME/.arkade/bin:$WDC_DO_COMMANDS_BIN:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/bin:.:$HOME/go/bin:$HOME/nbin:$HOME/node_modules/.bin:/snap/bin:$HOME/.krew/bin:$HOME/.fzf/bin


    PATH=$PATH:/opt/$TOOLCHAIN/bin

    export PROJECT_VARS="INSTALL_MOD_PATH ARCH TOOLCHAIN CROSS_COMPILE PATH"
}
