#!/usr/bin/env bash

# Usage help function
cmd=`basename $0`

function usage() {
		echo "Usage: $cmd [-h] <ip> <port>"
		echo "where:"
		echo "       -h                          : print this help"
}

# Arguments processing
while getopts hqnve:f flag
do
case $flag in
		h)
				usage
				exit
		;;
		?)
				usage
				exit
		;;
esac
done
shift $(( OPTIND - 1 ))  # shift to the last flag or argument

if [ $# -ne 2 ]; then
		usage
		exit
fi

IP="$1"
PORT="$2"

(echo > /dev/tcp/$IP/$PORT) >/dev/null 2>&1     && echo "It's up" || echo "It's down"
